// ============================================================================
// wrap-panel-studio  —  ISOLATED print-ready vehicle-wrap panel generator
// ----------------------------------------------------------------------------
// Built from scratch. Imports NOTHING from the existing render pipeline
// (no _shared/*, no studio-os, no panelizer). Self-contained on purpose.
//
// What it produces, per panel:
//   1. A clean, branding-free wrap BACKGROUND generated by Gemini, then the
//      edge pixels are CLONED outward to fill a true 2" bleed margin so the
//      panel trims with zero white edge.
//   2. The logo / graphic design elements as SEPARATE TRANSPARENT PNG overlays
//      (text layers are stored as editable vector metadata, exported to
//      transparent PNG client-side). The background carries NO baked-in
//      branding — the single source of truth, sliced cleanly per panel.
//
// Actions (single endpoint, `action` field):
//   generate | list | update | delete
// ============================================================================

import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Image } from "https://deno.land/x/imagescript@1.2.17/mod.ts";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...cors, "Content-Type": "application/json" },
  });

const MODEL = "gemini-3-pro-image-preview";
const BUCKET = "wrap-files";
const PREFIX = "wrap-panel-studio";
const LIVE_LONG = 1600; // long-side px of the generated "live" (trim) area
const ADMIN_EMAILS = ["trish@weprintwraps.com"];

// RECREATE MODE = pure reproduction (RecreatePro logic, reversed onto a panel).
// Deterministic: zero creativity so the design comes back 1:1, never redrawn.
const REPRO_TEMP = 0.0;
const REPRO_TOP_P = 1.0;
const REPRO_PERSONA =
  `You are a precise pre-press print production engine at WePrintWraps.com. ` +
  `You analyze approved vehicle wrap design references and isolate flat panel assets with zero artistic modification.\n\n` +
  `### Core Constraints\n` +
  `1. NO AI DRIFT: Maintain absolute alignment, scale, and spatial positions of all graphic elements exactly as seen in the reference anchor image.\n` +
  `2. TEMPERATURE ENFORCEMENT: Process with an implied temperature of 0.0. Do not invent new elements, shadows, lighting, or background patterns.\n` +
  `3. You reproduce; you never design.`;

// ---------------------------------------------------------------------------
// Self-contained Gemini key pool (does not import the shared helper)
// ---------------------------------------------------------------------------
function geminiKeys(): string[] {
  const ks: string[] = [];
  const primary = Deno.env.get("GOOGLE_AI_API_KEY");
  if (primary) ks.push(primary);
  for (let i = 2; i <= 5; i++) {
    const k = Deno.env.get(`GOOGLE_AI_API_KEY_${i}`);
    if (k) ks.push(k);
  }
  if (ks.length === 0) {
    const alt = Deno.env.get("GEMINI_API_KEY");
    if (alt) ks.push(alt);
  }
  return ks;
}
let keyIdx = 0;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function b64ToBytes(b64: string): Uint8Array {
  const clean = b64.includes(",") ? b64.split(",")[1] : b64;
  const bin = atob(clean);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function svc() {
  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
}

async function requireAdmin(req: Request): Promise<boolean> {
  const auth = req.headers.get("Authorization") || "";
  const token = auth.replace(/^Bearer\s+/i, "");
  if (!token) return false;
  try {
    const anon = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: `Bearer ${token}` } } },
    );
    const { data: { user } } = await anon.auth.getUser();
    if (!user) return false;
    if (ADMIN_EMAILS.includes((user.email || "").toLowerCase())) return true;
    const { data } = await svc()
      .from("user_roles").select("role")
      .eq("user_id", user.id).in("role", ["admin", "tester"])
      .limit(1).maybeSingle();
    return !!data;
  } catch {
    return false;
  }
}

async function genImage(
  prompt: string,
  refs: { mime: string; data: string }[] = [],
  opts: { aspectRatio?: string; imageSize?: string; temperature?: number; topP?: number; refsFirst?: boolean; system?: string } = {},
): Promise<Uint8Array> {
  const pool = geminiKeys();
  if (pool.length === 0) throw new Error("No GOOGLE_AI_API_KEY configured");

  const imgParts = refs.map((r) => ({ inlineData: { mimeType: r.mime, data: r.data } }));
  const textPart = { text: prompt };
  // For faithful recreation, the source image leads and the instruction follows.
  const parts: unknown[] = opts.refsFirst ? [...imgParts, textPart] : [textPart, ...imgParts];

  const generationConfig: Record<string, unknown> = {
    responseModalities: ["TEXT", "IMAGE"],
    imageConfig: { aspectRatio: opts.aspectRatio || "16:9", imageSize: opts.imageSize || "2K" },
  };
  if (typeof opts.temperature === "number") generationConfig.temperature = opts.temperature;
  if (typeof opts.topP === "number") generationConfig.topP = opts.topP;

  const reqBody: Record<string, unknown> = { contents: [{ role: "user", parts }], generationConfig };
  if (opts.system) reqBody.system_instruction = { parts: [{ text: opts.system }] };

  let lastErr: unknown = null;
  for (let attempt = 0; attempt < pool.length + 1; attempt++) {
    const key = pool[keyIdx % pool.length];
    keyIdx++;
    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${key}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(reqBody),
        },
      );
      if (!res.ok) {
        lastErr = new Error(`Gemini ${res.status}: ${(await res.text()).slice(0, 300)}`);
        continue;
      }
      const j = await res.json();
      const cand = j?.candidates?.[0];
      const part = cand?.content?.parts?.find((p: { inlineData?: { data?: string } }) => p?.inlineData?.data);
      if (!part) {
        lastErr = new Error(`No image returned (finishReason=${cand?.finishReason || "unknown"})`);
        continue;
      }
      return b64ToBytes(part.inlineData.data);
    } catch (e) {
      lastErr = e;
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error("Gemini generation failed");
}

// Pick the supported Gemini aspect ratio closest to the source image, so a
// recreation is generated in (roughly) the same shape as the uploaded wrap.
function nearestAspect(w: number, h: number): string {
  const r = w / h;
  const opts: [string, number][] = [
    ["21:9", 21 / 9], ["16:9", 16 / 9], ["3:2", 1.5], ["4:3", 4 / 3],
    ["1:1", 1], ["3:4", 0.75], ["2:3", 2 / 3], ["9:16", 9 / 16],
  ];
  let best = opts[0][0];
  let bd = Infinity;
  for (const [name, ratio] of opts) {
    const d = Math.abs(Math.log(r / ratio));
    if (d < bd) { bd = d; best = name; }
  }
  return best;
}

// Resize-to-cover then center-crop to exactly w×h (no distortion).
function cover(img: Image, w: number, h: number): Image {
  const scale = Math.max(w / img.width, h / img.height);
  const rw = Math.max(w, Math.ceil(img.width * scale));
  const rh = Math.max(h, Math.ceil(img.height * scale));
  img.resize(rw, rh);
  const x = Math.floor((rw - w) / 2);
  const y = Math.floor((rh - h) / 2);
  img.crop(x, y, w, h);
  return img;
}

// Clone the live-area edge pixels outward to fill a `bleed` margin on all
// four sides + corners. This is the true 2" bleed: the background extends
// past the trim line so there is no white edge after cutting.
function addClonedBleed(live: Image, bleed: number): Image {
  const lw = live.width;
  const lh = live.height;
  const W = lw + bleed * 2;
  const H = lh + bleed * 2;
  const canvas = new Image(W, H);
  canvas.composite(live, bleed, bleed);

  // sides (1px edge strip stretched across the bleed)
  canvas.composite(live.clone().crop(0, 0, 1, lh).resize(bleed, lh), 0, bleed);              // left
  canvas.composite(live.clone().crop(lw - 1, 0, 1, lh).resize(bleed, lh), bleed + lw, bleed); // right
  canvas.composite(live.clone().crop(0, 0, lw, 1).resize(lw, bleed), bleed, 0);              // top
  canvas.composite(live.clone().crop(0, lh - 1, lw, 1).resize(lw, bleed), bleed, bleed + lh); // bottom

  // corners
  canvas.composite(live.clone().crop(0, 0, 1, 1).resize(bleed, bleed), 0, 0);                       // TL
  canvas.composite(live.clone().crop(lw - 1, 0, 1, 1).resize(bleed, bleed), bleed + lw, 0);         // TR
  canvas.composite(live.clone().crop(0, lh - 1, 1, 1).resize(bleed, bleed), 0, bleed + lh);         // BL
  canvas.composite(live.clone().crop(lw - 1, lh - 1, 1, 1).resize(bleed, bleed), bleed + lw, bleed + lh); // BR

  return canvas;
}

async function upload(path: string, bytes: Uint8Array, mime = "image/png"): Promise<string> {
  const sb = svc();
  const { error } = await sb.storage.from(BUCKET).upload(path, bytes, {
    contentType: mime,
    upsert: true,
  });
  if (error) throw error;
  return sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;
}

function bytesToB64(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}

// Fetch an existing image URL (e.g. a DesignPro-stored master or view render)
// into a Gemini-ready ref. Read-only consumption of existing assets.
async function fetchToRef(url: string): Promise<{ mime: string; data: string }> {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`fetch ${r.status}`);
  const buf = new Uint8Array(await r.arrayBuffer());
  return { mime: r.headers.get("content-type") || "image/png", data: bytesToB64(buf) };
}

// Knock out pure magenta (#FF00FF) → transparent. Used to turn the AI "elements
// on magenta" pass into a real transparent-PNG overlay layer.
function chromaKeyMagenta(img: Image): Image {
  for (const [x, y, color] of img.iterateWithColors()) {
    const r = (color >>> 24) & 0xff, g = (color >>> 16) & 0xff, b = (color >>> 8) & 0xff;
    if (r > 180 && g < 90 && b > 180) img.setPixelAt(x, y, 0x00000000);
  }
  return img;
}

// LAYERS pass prompts (RecreatePro Mode B) — short, positive, deterministic.
const ELEMENTS_PROMPT =
  `From the attached approved vehicle wrap design, extract ONLY the graphic elements — logos, text lockups, mascots and focal graphics — exactly as they appear: same shapes, colors, proportions and relative positions. Paint them over a solid pure magenta #FF00FF background, with pure magenta everywhere there is no element, so they can be cut out as a transparent overlay. Crisp edges, elements only.`;
const BACKGROUND_PROMPT =
  `Reproduce the attached approved vehicle wrap design as ONE flat, full-bleed 2D background panel with the logos, text and focal graphics removed and the underlying pattern continued seamlessly where they were. Keep the exact colors, pattern, gradients and flow, edge to edge. Output the flat background artwork only.`;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
interface PanelSpec { name: string; widthIn: number; heightIn: number; sourceBase64?: string; sourceMime?: string; sourceUrl?: string }
interface TextEl { text: string; font?: string; color?: string; xPct?: number; yPct?: number; scale?: number }
interface Overlay {
  id: string;
  type: "logo" | "graphic" | "text";
  label: string;
  url?: string;
  text?: string;
  font?: string;
  color?: string;
  xPct: number;
  yPct: number;
  scale: number;
  rotation: number;
}

// ---------------------------------------------------------------------------
// generate
// ---------------------------------------------------------------------------
async function handleGenerate(body: Record<string, unknown>) {
  const vehicle = String(body.vehicle || "").trim();
  const designBrief = String(body.designBrief || "").trim();
  const finish = String(body.finish || "gloss").trim();
  const projectName = String(body.projectName || vehicle || "Untitled Project").trim();
  const bleedIn = Number(body.bleedIn ?? 2) || 2;
  const dpi = Number(body.dpi ?? 300) || 300;
  const panels = (body.panels as PanelSpec[]) || [];
  const textElements = (body.textElements as TextEl[]) || [];
  const graphicElements = (body.graphicElements as string[]) || [];
  const refRaw = body.referenceBase64 ?? body.styleReferenceBase64;
  let reference: { mime: string; data: string } | null = refRaw ? {
    mime: String(body.referenceMime || body.styleReferenceMime || "image/png"),
    data: String(refRaw).includes(",") ? String(refRaw).split(",")[1] : String(refRaw),
  } : null;
  // Consume a VisionBoardIQ asset by URL (read-only; nothing in DesignPro changes).
  if (!reference && body.referenceUrl) {
    try { reference = await fetchToRef(String(body.referenceUrl)); }
    catch (e) { console.error("referenceUrl fetch failed:", e); }
  }
  // VisionBoardIQ intent → mode. exact_reference = deterministic 1:1 copy;
  // style_inspiration = AI design in that style.
  const intent = String(body.visionboardIntent || body.intent || "");
  const mode = String(
    body.mode ||
    (intent === "exact_reference" ? "recreate"
      : intent === "style_inspiration" ? "inspire"
      : (reference ? "recreate" : "inspire")),
  );
  // "deterministic" = panels are CODE-cropped/scaled from the real 1:1 source
  // pixels (no per-panel AI → no drift → actually 1:1). "ai" = flatten a curved
  // 3D view with the model (look-alike, may drift) — only when no flat source.
  const splitMode = String(body.splitMode || "deterministic");

  if (!vehicle) return json({ error: "vehicle is required" }, 400);
  if (!Array.isArray(panels) || panels.length === 0) {
    return json({ error: "at least one panel { name, widthIn, heightIn } is required" }, 400);
  }

  const batchId = crypto.randomUUID();
  const sb = svc();

  // --- Build the SHARED overlay layers once (separate transparent PNGs) ---
  const overlays: Overlay[] = [];

  // ── CLONE step (RecreatePro Mode B): one AI call for the clean background,
  // one for the elements → chroma-keyed to a transparent PNG. Store this first
  // set; it is the editable layer pack and the 1:1 anchor for the split. ──
  let cleanBackgroundUrl: string | null = null;
  let elementsUrl: string | null = null;
  let combinedUrl: string | null = null;
  if (mode === "recreate" && reference) {
    const reproOpts = {
      aspectRatio: "16:9", imageSize: "2K",
      temperature: REPRO_TEMP, topP: REPRO_TOP_P, system: REPRO_PERSONA, refsFirst: true,
    } as const;
    let bgImg: Image | null = null;
    try {
      const bgBytes = await genImage(BACKGROUND_PROMPT, [reference], reproOpts);
      bgImg = await Image.decode(bgBytes);
      cleanBackgroundUrl = await upload(`${PREFIX}/${batchId}/clean-background.png`, bgBytes);
    } catch (e) { console.error("clone: background pass failed:", e); }

    let elImg: Image | null = null;
    try {
      const elBytes = await genImage(ELEMENTS_PROMPT, [reference], reproOpts);
      elImg = chromaKeyMagenta(await Image.decode(elBytes));
      elementsUrl = await upload(`${PREFIX}/${batchId}/elements.png`, await elImg.encode());
      overlays.push({
        id: crypto.randomUUID(), type: "graphic", label: "Lifted elements (transparent)",
        url: elementsUrl, xPct: 50, yPct: 50, scale: 1, rotation: 0,
      });
    } catch (e) { console.error("clone: elements pass failed:", e); }

    // combined = background + elements, proving the layers reassemble 1:1.
    if (bgImg) {
      try {
        const combined = bgImg.clone();
        if (elImg) {
          if (elImg.width !== combined.width || elImg.height !== combined.height) {
            elImg.resize(combined.width, combined.height);
          }
          combined.composite(elImg, 0, 0);
        }
        combinedUrl = await upload(`${PREFIX}/${batchId}/combined-master.png`, await combined.encode());
      } catch (e) { console.error("clone: combine failed:", e); }
    }
  }

  if (body.logoBase64) {
    const url = await upload(`${PREFIX}/${batchId}/logo.png`, b64ToBytes(String(body.logoBase64)));
    overlays.push({
      id: crypto.randomUUID(), type: "logo", label: "Logo", url,
      xPct: 50, yPct: 50, scale: 1, rotation: 0,
    });
  }

  for (let i = 0; i < graphicElements.length; i++) {
    const desc = String(graphicElements[i] || "").trim();
    if (!desc) continue;
    const bytes = await genImage(
      `Isolated vehicle-wrap design element: ${desc}. Centered on a FULLY TRANSPARENT background with a real alpha channel — no backdrop, no scene, no border, no surrounding color, no text or words. Crisp clean edges, suitable as a standalone PNG overlay layer.`,
    );
    const url = await upload(`${PREFIX}/${batchId}/graphic-${i}.png`, bytes);
    overlays.push({
      id: crypto.randomUUID(), type: "graphic", label: desc.slice(0, 40), url,
      xPct: 50, yPct: 50, scale: 1, rotation: 0,
    });
  }

  for (const t of textElements) {
    if (!t?.text) continue;
    overlays.push({
      id: crypto.randomUUID(), type: "text", label: t.text,
      text: t.text, font: t.font || "Oswald", color: t.color || "#ffffff",
      xPct: t.xPct ?? 50, yPct: t.yPct ?? 85, scale: t.scale ?? 1, rotation: 0,
    });
  }

  // --- Generate one cloned-background panel per panel spec ---
  const rows: unknown[] = [];
  for (const p of panels) {
    const widthIn = Number(p.widthIn) || 1;
    const heightIn = Number(p.heightIn) || 1;

    // Per-panel source view (drives faithful 1:1 recreation of THIS panel).
    // Falls back to the global reference when a panel has no view of its own.
    const panelSrcRaw = p.sourceBase64;
    let panelSrc: { mime: string; data: string } | null = panelSrcRaw
      ? {
        mime: String(p.sourceMime || "image/png"),
        data: String(panelSrcRaw).includes(",") ? String(panelSrcRaw).split(",")[1] : String(panelSrcRaw),
      }
      : null;
    // Per-panel VisionBoardIQ view render by URL (the 7 saved views).
    if (!panelSrc && p.sourceUrl) {
      try { panelSrc = await fetchToRef(String(p.sourceUrl)); }
      catch (e) { console.error(`panel ${p.name} sourceUrl fetch failed:`, e); }
    }
    // Fall back to the master/reference for the 1:1 split when a panel has no view.
    if (!panelSrc) panelSrc = (mode === "recreate" ? reference : null);

    let backgroundUrl: string | null = null;
    let status = "complete";
    try {
      // live (trim) area at true panel aspect
      let liveW: number, liveH: number;
      if (widthIn >= heightIn) {
        liveW = LIVE_LONG;
        liveH = Math.max(1, Math.round(LIVE_LONG * heightIn / widthIn));
      } else {
        liveH = LIVE_LONG;
        liveW = Math.max(1, Math.round(LIVE_LONG * widthIn / heightIn));
      }

      let decoded: Image;
      if (mode === "recreate" && panelSrc && splitMode === "deterministic") {
        // TRUE 1:1 SPLIT — use the real source pixels directly. The AI never
        // regenerates the panel, so nothing drifts; cover() only scales/crops
        // the actual artwork to the panel's true aspect. This is the only way
        // to get genuinely 1:1 panels (an image generator always repaints).
        decoded = await Image.decode(b64ToBytes(panelSrc.data));
      } else if (mode === "recreate" && panelSrc) {
        // AI FLATTEN (look-alike, can drift) — only when the source is a curved
        // 3D view rather than a flat panel, and the caller opts into splitMode:"ai".
        const reproPrompt =
          `Analyze the provided vehicle wrap design reference and isolate the flat panel asset for the ${p.name} with zero artistic modification. ` +
          `Maintain absolute alignment, scale, and spatial positions of all graphic elements exactly as seen in the reference anchor image. ` +
          `Do not invent new elements, shadows, lighting, or background patterns. ` +
          `Render that view flattened as ONE full-bleed 2D wrap panel, edge to edge, as if peeled off the vehicle and laid flat. Finish: ${finish}. ` +
          `Output only that panel's flat artwork.`;
        const raw = await genImage(reproPrompt, [panelSrc], {
          aspectRatio: nearestAspect(widthIn, heightIn),
          imageSize: "2K", temperature: REPRO_TEMP, topP: REPRO_TOP_P, system: REPRO_PERSONA, refsFirst: true,
        });
        decoded = await Image.decode(raw);
      } else {
        // Original / "inspire" path — generate an original design (optionally in
        // the style of the global reference).
        const bgPrompt =
          `Flat 2D vehicle-wrap background artwork for the "${p.name}" panel of a ${vehicle}. ` +
          `${designBrief ? designBrief + ". " : ""}${finish} finish. ` +
          `It is the printable wrap GRAPHIC ITSELF as a flat artboard that fills the entire frame edge to edge — ` +
          `NO vehicle, NO car, NO mockup, NO logos, NO text, NO words, NO watermark. ` +
          `Cohesive palette, rich detail, seamless full-bleed composition that reads cleanly across a very large format panel.` +
          (reference ? ` Match the style, palette and mood of the provided reference image.` : ``);
        const raw = await genImage(bgPrompt, reference ? [reference] : []);
        decoded = await Image.decode(raw);
      }

      const live = cover(decoded, liveW, liveH);

      // 2" bleed cloned outward
      const bleedPx = Math.max(
        4,
        Math.round((bleedIn / Math.max(widthIn, heightIn)) * LIVE_LONG),
      );
      const panel = addClonedBleed(live, bleedPx);
      const png = await panel.encode();
      backgroundUrl = await upload(`${PREFIX}/${batchId}/panel-${p.name.replace(/[^a-z0-9]+/gi, "_")}.png`, png);
    } catch (e) {
      console.error("panel generation failed:", p.name, e);
      status = "error";
    }

    const { data, error } = await sb.from("wrap_panel_artboards").insert({
      batch_id: batchId,
      project_name: projectName,
      vehicle,
      design_brief: designBrief,
      finish,
      panel_name: p.name,
      width_in: widthIn,
      height_in: heightIn,
      bleed_in: bleedIn,
      dpi,
      background_url: backgroundUrl,
      overlays,
      status,
      metadata: {
        live_long: LIVE_LONG,
        mode,
        split_mode: splitMode,
        clean_background_url: cleanBackgroundUrl,
        elements_url: elementsUrl,
        combined_url: combinedUrl,
      },
    }).select().single();

    if (error) {
      console.error("insert failed:", error);
      return json({ error: "Failed to save artboard: " + error.message }, 500);
    }
    rows.push(data);
  }

  return json({ success: true, batchId, artboards: rows });
}

// ---------------------------------------------------------------------------
// list / update / delete
// ---------------------------------------------------------------------------
async function handleList() {
  const { data, error } = await svc()
    .from("wrap_panel_artboards")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(500);
  if (error) return json({ error: error.message }, 500);
  return json({ success: true, artboards: data });
}

async function handleUpdate(body: Record<string, unknown>) {
  const id = String(body.id || "");
  if (!id) return json({ error: "id is required" }, 400);
  const patch: Record<string, unknown> = {};
  if (body.overlays !== undefined) patch.overlays = body.overlays;
  if (body.project_name !== undefined) patch.project_name = body.project_name;
  if (body.design_brief !== undefined) patch.design_brief = body.design_brief;
  if (body.width_in !== undefined) patch.width_in = body.width_in;
  if (body.height_in !== undefined) patch.height_in = body.height_in;
  if (body.bleed_in !== undefined) patch.bleed_in = body.bleed_in;
  if (Object.keys(patch).length === 0) return json({ error: "nothing to update" }, 400);

  const { data, error } = await svc()
    .from("wrap_panel_artboards").update(patch).eq("id", id).select().single();
  if (error) return json({ error: error.message }, 500);
  return json({ success: true, artboard: data });
}

async function handleDelete(body: Record<string, unknown>) {
  const sb = svc();
  if (body.batchId) {
    const { error } = await sb.from("wrap_panel_artboards").delete().eq("batch_id", String(body.batchId));
    if (error) return json({ error: error.message }, 500);
    return json({ success: true });
  }
  const id = String(body.id || "");
  if (!id) return json({ error: "id or batchId is required" }, 400);
  const { error } = await sb.from("wrap_panel_artboards").delete().eq("id", id);
  if (error) return json({ error: error.message }, 500);
  return json({ success: true });
}

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------
serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: cors });

  try {
    if (!(await requireAdmin(req))) {
      return json({ error: "Admin access required" }, 403);
    }
    const body = await req.json().catch(() => ({}));
    const action = String(body.action || "generate");

    switch (action) {
      case "generate": return await handleGenerate(body);
      case "list": return await handleList();
      case "update": return await handleUpdate(body);
      case "delete": return await handleDelete(body);
      default: return json({ error: `Unknown action: ${action}` }, 400);
    }
  } catch (e) {
    console.error("wrap-panel-studio error:", e);
    return json({ error: e instanceof Error ? e.message : "Unexpected failure" }, 500);
  }
});
