/**
 * ═══════════════════════════════════════════════════════
 *  EXTRACT → VECTORIZE → SIZE
 *  RestyleProAI ProductionFlow™ — Print-Ready Pipeline
 * ═══════════════════════════════════════════════════════
 *
 *  INPUT:  GENIE overlay screenshot (3D render + cyan panel rectangle)
 *          — Already generated by Universal Panelizer for every panel
 *
 *  STEP 1: EXTRACT — Gemini sees the overlay, extracts ONLY the art
 *          inside the cyan rectangle, outputs it flat edge-to-edge.
 *          NOT creating. NOT interpreting. EXTRACTING.
 *
 *  STEP 2: VECTORIZE — Vectorizer.AI converts raster → EPS
 *          Deterministic. Same input = same output. Every time.
 *
 *  STEP 3: SIZE — Set artboard to exact production dims from
 *          vehicle spreadsheet. Vector = lossless resize. Done.
 *
 *  OUTPUT: Print-ready EPS at 10% scale, ready for RIP.
 *          No ESRGAN. No DPI math. No upscaling. No guessing.
 * ═══════════════════════════════════════════════════════
 */


// ─── STEP 1: EXTRACT ─────────────────────────────────

/**
 * The extraction prompt. This is the IP.
 *
 * Gemini receives ONE image: the GENIE overlay screenshot
 * showing the 3D wrapped vehicle with a cyan rectangle
 * marking the panel boundary. Its job is surgical extraction.
 */
function buildExtractionPrompt(panelName: string, panelLabel: string): string {
  return `You are a vehicle wrap production technician extracting print-ready panel artwork.

You are looking at a photograph of a wrapped vehicle with a CYAN/TURQUOISE RECTANGLE overlaid on it. This rectangle marks the "${panelLabel}" panel boundary.

YOUR TASK — Extract the artwork:
1. Identify ALL the wrap artwork visible INSIDE the cyan rectangle
2. Reproduce that artwork as a FLAT 2D image filling the ENTIRE output canvas edge-to-edge
3. The background color/pattern of the wrap MUST extend to ALL edges (full bleed)
4. Match the colors, patterns, gradients, and design elements EXACTLY as they appear on the vehicle

CRITICAL RULES:
- Output ONLY the flat panel artwork — NO vehicle body, NO wheels, NO windows, NO chrome
- NO perspective, NO 3D curves, NO reflections, NO shadows from the vehicle surface
- NO cyan/turquoise rectangle lines in the output
- The artwork should look like vinyl laying FLAT on a cutting table before installation
- Fill the ENTIRE canvas — no white borders, no empty space
- The output aspect ratio should match the proportions of the cyan rectangle you see
- If text/logos are visible in the panel area, include them at correct position and scale
- Design elements that extend beyond the cyan boundary: continue/extend them to the canvas edge
- Think: "What would this panel look like if I peeled the vinyl off the car and laid it flat?"

OUTPUT: A single flat rectangular image. Edge to edge. Full bleed. Production ready.`;
}

/**
 * Extract flat panel art from a GENIE overlay screenshot
 *
 * @param overlayImageBase64 - The GENIE screenshot with cyan panel rectangle
 * @param panelName - Panel key (driver_side, hood, etc.)
 * @param panelLabel - Display label from the overlay (e.g., "PASSENGER SIDE (XL)")
 * @param apiKey - Gemini API key
 * @returns Base64 raster image of the extracted flat panel
 */
async function extractPanel(
  overlayImageBase64: string,
  panelName: string,
  panelLabel: string,
  apiKey: string
): Promise<{ imageBase64: string; mimeType: string }> {

  const prompt = buildExtractionPrompt(panelName, panelLabel);

  // Call Gemini with the overlay screenshot
  const response = await fetch(
    // gemini-2.5-pro-preview-05-06 retired by Google; this call emits an IMAGE,
    // so use the sanctioned primary image model (_shared/model-config.ts).
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{
          parts: [
            { text: prompt },
            {
              inlineData: {
                mimeType: "image/png",
                data: overlayImageBase64
              }
            }
          ]
        }],
        generationConfig: {
          responseModalities: ["IMAGE", "TEXT"],
          temperature: 0.1, // Low creativity — we want exact extraction
        }
      })
    }
  );

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`EXTRACT: Gemini ${response.status}: ${errText}`);
  }

  const data = await response.json();
  const parts = data?.candidates?.[0]?.content?.parts || [];
  const imagePart = parts.find((p: any) => p.inlineData);

  if (!imagePart?.inlineData?.data) {
    const textParts = parts.filter((p: any) => p.text).map((p: any) => p.text);
    console.error("EXTRACT: No image returned. Text response:", textParts.join(" "));
    throw new Error(`EXTRACT: Gemini returned no image for ${panelName}`);
  }

  console.log(`✅ EXTRACT: ${panelName} — flat panel extracted`);

  return {
    imageBase64: imagePart.inlineData.data,
    mimeType: imagePart.inlineData.mimeType || "image/png"
  };
}


// ─── STEP 2: VECTORIZE ──────────────────────────────

/**
 * Convert extracted raster panel to production vector EPS
 * using Vectorizer.AI (deterministic, same in = same out)
 *
 * @param imageBase64 - Extracted flat panel raster
 * @param panelName - Panel identifier
 * @param options - API credentials
 * @returns EPS file bytes
 */
async function vectorizePanel(
  imageBase64: string,
  panelName: string,
  options: { apiId: string; apiSecret: string }
): Promise<{ epsBytes: Uint8Array; imageToken?: string }> {

  // Decode base64 to bytes
  const imageBytes = Uint8Array.from(atob(imageBase64), c => c.charCodeAt(0));

  // Build form data
  const formData = new FormData();
  formData.append("image", new Blob([imageBytes], { type: "image/png" }), `${panelName}.png`);

  // Output: EPS — universal RIP compatibility
  formData.append("output.file_format", "eps");
  formData.append("mode", "production");

  // Shape stacking: stacked = smaller files, cleaner output
  formData.append("output.shape_stacking", "stacked");
  formData.append("output.draw_style", "fill");

  // Gap filler: CRITICAL for print — no white lines between shapes
  formData.append("output.gap_filler.enabled", "true");
  formData.append("output.gap_filler.non_scaling_stroke", "true");
  formData.append("output.gap_filler.stroke_width", "2.0");

  // Curve quality: fine for wrap art (clean curves, accurate shapes)
  formData.append("processing.line_fit_tolerance", "fine");

  // All curve types enabled for best quality
  formData.append("processing.allowed_curve_types.lines", "true");
  formData.append("processing.allowed_curve_types.circular_arcs", "true");
  formData.append("processing.allowed_curve_types.elliptical_arcs", "true");
  formData.append("processing.allowed_curve_types.cubic_bezier_curves", "true");

  // API call
  const authHeader = "Basic " + btoa(`${options.apiId}:${options.apiSecret}`);

  const response = await fetch("https://vectorizer.ai/api/v1/vectorize", {
    method: "POST",
    headers: { Authorization: authHeader },
    body: formData,
  });

  if (!response.ok) {
    const errBody = await response.text();
    if (response.status === 402) {
      throw new Error("VECTORIZE: Out of credits — upgrade at vectorizer.ai/pricing");
    }
    throw new Error(`VECTORIZE: API error ${response.status}: ${errBody}`);
  }

  const epsBytes = new Uint8Array(await response.arrayBuffer());
  const imageToken = response.headers.get("X-Image-Token") || undefined;

  console.log(`✅ VECTORIZE: ${panelName} — ${(epsBytes.length / 1024).toFixed(0)}KB EPS`);

  return { epsBytes, imageToken };
}


// ─── STEP 3: SIZE ────────────────────────────────────

/**
 * Panel dimension specs from the vehicle spreadsheet.
 * All dimensions in INCHES, full size, including 3" bleed per side.
 *
 * At 10% scale: multiply each dimension by 0.1
 * In the EPS/PDF: set artboard to (inches × 0.1 × 72) points
 *
 * These are DEFAULTS — actual dims come from the vehicle
 * dimensions database per make/model/year.
 */
const DEFAULT_PANEL_DIMS: Record<string, { widthIn: number; heightIn: number }> = {
  driver_side:    { widthIn: 165, heightIn: 54 },
  passenger_side: { widthIn: 165, heightIn: 54 },
  side_small:     { widthIn: 144, heightIn: 48 },
  side_medium:    { widthIn: 172, heightIn: 54 },
  side_large:     { widthIn: 200, heightIn: 54 },
  side_xl:        { widthIn: 240, heightIn: 59.5 },
  hood:           { widthIn: 70,  heightIn: 59 },
  roof:           { widthIn: 54,  heightIn: 65 },
  trunk:          { widthIn: 58,  heightIn: 36 },
  front_bumper:   { widthIn: 126, heightIn: 35 },
  rear_bumper:    { widthIn: 134, heightIn: 29 },
  rear_hatch:     { widthIn: 64,  heightIn: 42 },
};

/**
 * Stamp the EPS with production dimensions.
 *
 * For now: returns the EPS bytes unchanged + metadata.
 * The RIP software reads the EPS at whatever size and scales.
 * The metadata travels with the file for the print operator.
 *
 * For full production: use a PostScript library to rewrite
 * the EPS BoundingBox to exact dims at 10% scale.
 * That's a deterministic string replacement in the EPS header:
 *
 *   %%BoundingBox: 0 0 <width_pts> <height_pts>
 *   where width_pts = widthInches × 0.1 × 72
 *
 * @param epsBytes - Vector EPS from Vectorizer.AI
 * @param panelName - Panel identifier
 * @param vehicleDims - Optional exact dims from vehicle DB
 * @returns Sized EPS bytes + production metadata
 */
function sizePanel(
  epsBytes: Uint8Array,
  panelName: string,
  vehicleDims?: { widthIn: number; heightIn: number }
): {
  epsBytes: Uint8Array;
  metadata: {
    panelName: string;
    fullSizeWidth: string;
    fullSizeHeight: string;
    tenthScaleWidth: string;
    tenthScaleHeight: string;
    boundingBoxPts: string;
  }
} {
  const dims = vehicleDims || DEFAULT_PANEL_DIMS[panelName];
  if (!dims) {
    throw new Error(`SIZE: No dimensions found for panel "${panelName}"`);
  }

  // 10% scale in points (72 pts/inch)
  const widthPts = Math.round(dims.widthIn * 0.1 * 72);   // e.g., 165" → 1188 pts
  const heightPts = Math.round(dims.heightIn * 0.1 * 72);  // e.g., 54" → 388.8 pts

  // Rewrite EPS BoundingBox if present
  const epsString = new TextDecoder().decode(epsBytes);
  const bbRegex = /%%BoundingBox:\s*[\d\s.]+/;

  let sizedEps: Uint8Array;
  if (bbRegex.test(epsString)) {
    const newBB = `%%BoundingBox: 0 0 ${widthPts} ${heightPts}`;
    const updatedEps = epsString.replace(bbRegex, newBB);

    // Also update HiResBoundingBox if present
    const hrbbRegex = /%%HiResBoundingBox:\s*[\d\s.]+/;
    const finalEps = hrbbRegex.test(updatedEps)
      ? updatedEps.replace(hrbbRegex, `%%HiResBoundingBox: 0 0 ${widthPts}.00 ${heightPts}.00`)
      : updatedEps;

    sizedEps = new TextEncoder().encode(finalEps);
    console.log(`✅ SIZE: ${panelName} — BoundingBox set to ${widthPts}×${heightPts} pts (${dims.widthIn}"×${dims.heightIn}" at 10%)`);
  } else {
    // No BoundingBox found — return as-is with metadata
    sizedEps = epsBytes;
    console.warn(`⚠️ SIZE: ${panelName} — No BoundingBox found in EPS, metadata only`);
  }

  return {
    epsBytes: sizedEps,
    metadata: {
      panelName,
      fullSizeWidth: `${dims.widthIn}"`,
      fullSizeHeight: `${dims.heightIn}"`,
      tenthScaleWidth: `${(dims.widthIn * 0.1).toFixed(1)}"`,
      tenthScaleHeight: `${(dims.heightIn * 0.1).toFixed(1)}"`,
      boundingBoxPts: `${widthPts} × ${heightPts} pts`,
    }
  };
}


// ═══════════════════════════════════════════════════════
// MAIN PIPELINE: EXTRACT → VECTORIZE → SIZE
// ═══════════════════════════════════════════════════════

export interface PanelInput {
  /** GENIE overlay screenshot (base64) — 3D render with cyan panel rectangle */
  overlayImageBase64: string;
  /** Panel key: driver_side, hood, roof, etc. */
  panelName: string;
  /** Display label from the overlay: "PASSENGER SIDE (XL)" */
  panelLabel: string;
  /** Optional: exact dims from vehicle database (full-size inches w/ bleed) */
  vehicleDims?: { widthIn: number; heightIn: number };
}

export interface PanelOutput {
  /** Production-ready EPS bytes, sized to spec */
  epsBytes: Uint8Array;
  /** Storage path for Supabase upload */
  storagePath: string;
  /** MIME type */
  mimeType: string;
  /** Production metadata */
  metadata: Record<string, string>;
  /** Vectorizer.AI image token (for downloading SVG/PDF versions) */
  imageToken?: string;
  /** Processing time */
  processingTimeMs: number;
}

/**
 * Run the full EXTRACT → VECTORIZE → SIZE pipeline for one panel.
 * Call this once per panel in the panelizer loop.
 */
export async function processPanel(
  input: PanelInput,
  jobId: string,
  config: {
    geminiApiKey: string;
    vectorizerApiId: string;
    vectorizerApiSecret: string;
  }
): Promise<PanelOutput> {
  const startTime = Date.now();
  console.log(`\n🔧 [${jobId}] ━━━ ${input.panelName.toUpperCase()} ━━━`);

  // ── STEP 1: EXTRACT ──
  console.log(`  📐 EXTRACT: Sending overlay to Gemini...`);
  const extracted = await extractPanel(
    input.overlayImageBase64,
    input.panelName,
    input.panelLabel,
    config.geminiApiKey
  );

  // ── STEP 2: VECTORIZE ──
  console.log(`  🔄 VECTORIZE: Sending to Vectorizer.AI...`);
  const vectorized = await vectorizePanel(
    extracted.imageBase64,
    input.panelName,
    {
      apiId: config.vectorizerApiId,
      apiSecret: config.vectorizerApiSecret,
    }
  );

  // ── STEP 3: SIZE ──
  console.log(`  📏 SIZE: Setting production dimensions...`);
  const sized = sizePanel(
    vectorized.epsBytes,
    input.panelName,
    input.vehicleDims
  );

  const elapsed = Date.now() - startTime;
  console.log(`  ✅ DONE: ${input.panelName} — ${(sized.epsBytes.length / 1024).toFixed(0)}KB EPS, ${elapsed}ms`);

  return {
    epsBytes: sized.epsBytes,
    storagePath: `panelizer/${jobId}/production-${input.panelName}.eps`,
    mimeType: "application/postscript",
    metadata: {
      ...sized.metadata,
      jobId,
      extractModel: "gemini-3-pro-image-preview",
      vectorizer: "vectorizer.ai",
      pipeline: "extract-vectorize-size",
      processingTimeMs: String(elapsed),
    },
    imageToken: vectorized.imageToken,
    processingTimeMs: elapsed,
  };
}


// ═══════════════════════════════════════════════════════
// PANELIZER INTEGRATION
// ═══════════════════════════════════════════════════════
//
// WHERE THIS PLUGS IN:
//
// The GENIE Universal Panelizer already generates overlay
// screenshots for every panel. Each screenshot shows:
//   - The 3D render of the wrapped vehicle
//   - A cyan rectangle marking the panel boundary
//   - Panel label (e.g., "DRIVER SIDE (MEDIUM)")
//   - Dimensions (e.g., "172" × 59.5"")
//
// Currently these screenshots are just for display.
// Now they become the INPUT to this pipeline.
//
// In the panelizer orchestrator (panelizer-os-orchestrator),
// after generating the overlay screenshots:
//
//   const panels = [
//     { overlayBase64: driverOverlay, panelName: "driver_side", panelLabel: "DRIVER SIDE (MEDIUM)" },
//     { overlayBase64: passengerOverlay, panelName: "passenger_side", panelLabel: "PASSENGER SIDE (MEDIUM)" },
//     { overlayBase64: hoodOverlay, panelName: "hood", panelLabel: "HOOD" },
//     { overlayBase64: roofOverlay, panelName: "roof", panelLabel: "ROOF" },
//     { overlayBase64: rearOverlay, panelName: "trunk", panelLabel: "TRUNK" },
//     { overlayBase64: frontBumperOverlay, panelName: "front_bumper", panelLabel: "FRONT BUMPER" },
//     { overlayBase64: rearBumperOverlay, panelName: "rear_bumper", panelLabel: "REAR BUMPER" },
//   ];
//
//   const results = [];
//   for (const panel of panels) {
//     const result = await processPanel(
//       {
//         overlayImageBase64: panel.overlayBase64,
//         panelName: panel.panelName,
//         panelLabel: panel.panelLabel,
//         // vehicleDims from DB lookup for this specific vehicle
//       },
//       jobId,
//       {
//         geminiApiKey: Deno.env.get("GOOGLE_AI_API_KEY"),
//         vectorizerApiId: Deno.env.get("VECTORIZER_AI_API_ID"),
//         vectorizerApiSecret: Deno.env.get("VECTORIZER_AI_API_SECRET"),
//       }
//     );
//
//     // Upload EPS to Supabase Storage
//     await uploadToStorage(result.storagePath, result.epsBytes, result.mimeType);
//     results.push(result);
//   }
//
// ═══════════════════════════════════════════════════════
//
// ENV VARS NEEDED (add to Supabase secrets):
//
//   GOOGLE_AI_API_KEY        — already exists
//   VECTORIZER_AI_API_ID     — from vectorizer.ai account
//   VECTORIZER_AI_API_SECRET — from vectorizer.ai account
//
//   npx supabase secrets set VECTORIZER_AI_API_ID=your_id
//   npx supabase secrets set VECTORIZER_AI_API_SECRET=your_secret
//
// ═══════════════════════════════════════════════════════
//
// WHAT GETS SKIPPED:
//
//   panelizer-step-extract  → REPLACED by this pipeline
//   panelizer-step-fill     → REPLACED by this pipeline
//   panelizer-step-upscale  → ELIMINATED (vector = infinite res)
//   ESRGAN                  → ELIMINATED (not needed for vectors)
//   DPI calculations        → ELIMINATED (vectors are resolution-independent)
//
// WHAT STAYS:
//
//   panelizer-step-scan     → Still scans render for panel regions
//   panelizer-step-stamp    → Adds metadata to EPS (minor mod)
//   panelizer-step-proof    → Generates proof sheet from EPS
//   Overlay screenshot gen  → ALREADY EXISTS — now serves dual purpose
//   Vehicle dims database   → ALREADY EXISTS — feeds SIZE step
//
// ═══════════════════════════════════════════════════════
//
// COST PER VEHICLE (7 panels):
//
//   Gemini extraction:    ~$0.04 × 7 = $0.28 (vision + image gen)
//   Vectorizer.AI:        ~$1.00 × 7 = $7.00 (production mode)
//   ─────────────────────────────────────────
//   Total:                         ~$7.28/vehicle
//
//   vs. current: $0.49 + 30-60 min manual cleanup
//   vs. manual designer: $500-975 per design
//
// ═══════════════════════════════════════════════════════
