import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const { uploadSpoolWithTus } = require("../../runtime/zip-spool.cjs");

const runId = "11111111-1111-4111-8111-111111111111";
const tenant = "user_22222222-2222-4222-8222-222222222222";
const material = "a".repeat(24);
const spool = {
  contentHash: "b".repeat(64),
  byteSize: 1,
  filePath: "/tmp/not-reached",
};
const supabase = {
  storage: {
    from() {
      return {
        download() {
          return Promise.resolve({ data: null, error: { status: 404, message: "not found" } });
        },
      };
    },
  },
};

async function observedCode(storagePath) {
  try {
    await uploadSpoolWithTus({
      supabase,
      supabaseUrl: "https://example.supabase.co",
      serviceRoleKey: "x".repeat(32),
      endpoint: "http://invalid.example/storage/v1/upload/resumable",
      spoolDir: "/tmp/not-reached",
      spool,
      storagePath,
      contentType: "image/png",
    });
  } catch (error) {
    return error.code;
  }
  return null;
}

test("TUS allowlist accepts the two exact Call 8 proof paths generated by runtime/index.js", async () => {
  const prefix = `designpro/${tenant}/${runId}/proof/`;
  assert.equal(
    await observedCode(`${prefix}flat-wrap-layout-${material}.png`),
    "tus_endpoint_invalid",
    "flat-wrap layout path must pass path validation before the deliberately invalid endpoint"
  );
  assert.equal(
    await observedCode(`${prefix}call8-2d-production-proof-${material}.png`),
    "tus_endpoint_invalid",
    "2D production proof path must pass path validation before the deliberately invalid endpoint"
  );
});

test("TUS allowlist remains fail-closed for arbitrary proof paths", async () => {
  const prefix = `designpro/${tenant}/${runId}/proof/`;
  assert.equal(await observedCode(`${prefix}anything-${material}.png`), "tus_storage_path_invalid");
  assert.equal(
    await observedCode(`designpro/${tenant}/${runId}/call8-flat-2d-proof.png`),
    "tus_storage_path_invalid",
    "obsolete root-level Call 8 path must not remain allowlisted"
  );
});
