/**
 * Bulk Prompt Generator
 *
 * Builds a queue of 25 render jobs by pairing prompts from the
 * preset library with vehicles from the Top 20 list.
 */

import {
  getPresetsByCategory,
  getRandomPresets,
  type PromptPreset,
} from "@/data/prompt-presets";
import {
  TOP_20_VEHICLES,
  getVehicleByIndex,
  formatVehicleName,
  type Vehicle,
} from "@/lib/vehicle-selection";

export const VIEW_ORDER = ["side", "passenger-side", "hood_detail", "front", "rear", "close-up", "roof"];
export const VIEW_LABELS: Record<string, string> = {
  side: "Driver Side",
  "passenger-side": "Passenger Side",
  hood_detail: "Hood",
  front: "Front",
  rear: "Rear",
  "close-up": "Close-Up",
  roof: "Roof Plan",
};

export interface RenderJob {
  id: string;
  /** Sequential order number for this batch job (e.g. "RP-001001") */
  orderNumber: string;
  prompt: PromptPreset;
  vehicle: Vehicle;
  finish: "Gloss" | "Satin" | "Matte";
  status: "queued" | "running" | "done" | "failed";
  renderUrl: string | null;
  panelUrl: string | null;
  generationId: string | null;
  /** Design anchor text for cross-view continuity (generated by generate-color-render) */
  designAnchorText: string | null;
  error: string | null;
  startedAt: number | null;
  durationMs: number | null;
  rating: number | null;
  /** All 7 views keyed by view type */
  views: Record<string, string>;
  viewsStatus: "none" | "running" | "done" | "partial";
  viewsProgress: number;
  version: number;
  /** Production pack */
  packUrl: string | null;
  packStatus: "none" | "running" | "done" | "failed";
  packError: string | null;
  /** Self-healing */
  healAttempts: number;
  healStatus: "none" | "retrying" | "healed" | "gave_up";
  healLog: string[];
}

const FINISHES: RenderJob["finish"][] = ["Gloss", "Satin", "Matte"];

/**
 * Map a commercial vehicle (van / pickup / SUV) to the Top-20 category
 * enum so we still get sensible panel-size defaults downstream. The
 * Top-20 list itself doesn't include vans, so anything unrecognised
 * falls back to "truck" which has the closest body proportions.
 */
function guessVehicleCategory(make: string, model: string): Vehicle["category"] {
  const m = `${make} ${model}`.toLowerCase();
  if (/odyssey|highlander|traverse|outback|pilot|telluride|ascent/.test(m)) return "suv";
  if (/transit|sprinter|promaster|express|nv200/.test(m)) return "truck";
  if (/silverado|sierra|f-1|f-2|f-3|f-4|tundra|titan|ram|tacoma|colorado|frontier|gladiator|maverick/.test(m)) return "truck";
  return "truck";
}

let _seq = 0;
/** Global order counter - persisted in localStorage so numbers never repeat across sessions */
let _orderSeq = (() => {
  try {
    return parseInt(localStorage.getItem("rp_order_seq") || "1000", 10);
  } catch {
    return 1000;
  }
})();

/** Generate next RP-XXXXXX order number */
export function nextOrderNumber(): string {
  _orderSeq++;
  try { localStorage.setItem("rp_order_seq", String(_orderSeq)); } catch { /* SSR safe */ }
  return `RP-${String(_orderSeq).padStart(6, "0")}`;
}

export function buildQueue(
  count: number,
  category: "restyle" | "commercial",
): RenderJob[] {
  const prompts = getRandomPresets(count, category);
  return buildQueueFromPrompts(prompts);
}

/**
 * Build a render queue from an explicit list of prompts. Used by the
 * AI-generated trade flow on AdminBulkDesignPro — the prompts come from
 * `generate-batch-prompts` rather than the static library, and each one
 * already carries its own `vehicle` (so we honour that instead of cycling
 * through `TOP_20_VEHICLES`).
 */
export function buildQueueFromPrompts(prompts: PromptPreset[]): RenderJob[] {
  return prompts.map((prompt, i) => ({
    id: `rj_${Date.now()}_${++_seq}`,
    orderNumber: nextOrderNumber(),
    prompt,
    vehicle: prompt.vehicle
      ? {
          year: prompt.vehicle.year,
          make: prompt.vehicle.make,
          model: prompt.vehicle.model,
          // Commercial trade prompts carry the vehicle but not the
          // Top-20 category enum. Best-effort guess so downstream
          // size lookups still work.
          category: guessVehicleCategory(prompt.vehicle.make, prompt.vehicle.model),
        }
      : getVehicleByIndex(i),
    finish: FINISHES[i % FINISHES.length],
    status: "queued",
    renderUrl: null,
    panelUrl: null,
    generationId: null,
    designAnchorText: null,
    error: null,
    startedAt: null,
    durationMs: null,
    rating: null,
    views: {},
    viewsStatus: "none",
    viewsProgress: 0,
    version: 1,
    packUrl: null,
    packStatus: "none",
    packError: null,
    healAttempts: 0,
    healStatus: "none",
    healLog: [],
  }));
}
