import jsPDF from 'jspdf';
import { PLATFORM_LABEL } from '@/lib/tool-registry';

export interface WrapCarePDFData {
  shopName: string;
  shopLogoUrl?: string | null;
  shopPhone?: string | null;
  shopEmail?: string | null;
  shopWebsite?: string | null;
  customerName?: string | null;
  vehicle?: {
    year?: string | null;
    make?: string | null;
    model?: string | null;
  };
  manufacturer?: string | null;
  colorName?: string | null;
  finish?: string | null;
  installDate?: string | null; // ISO string
}

// ── Colors ──────────────────────────────────────────────────────────────
const BLUE    = { r: 59,  g: 130, b: 246 }; // #3b82f6
const FUCHSIA = { r: 236, g: 72,  b: 153 }; // #ec4899
const DARK    = { r: 30,  g: 41,  b: 59  }; // #1e293b
const MUTED   = { r: 100, g: 116, b: 139 }; // #64748b
const LINE    = { r: 203, g: 213, b: 225 }; // #cbd5e1
const LIGHT   = { r: 241, g: 245, b: 249 }; // #f1f5f9
const WHITE   = { r: 255, g: 255, b: 255 };

// ── Helpers ─────────────────────────────────────────────────────────────

/** Load an image URL as a data-URL with its natural dimensions. */
function loadImageAsDataUrl(
  url: string
): Promise<{ dataUrl: string; width: number; height: number }> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = async () => {
      try {
        const res = await fetch(url);
        const blob = await res.blob();
        const reader = new FileReader();
        reader.onloadend = () =>
          resolve({
            dataUrl: reader.result as string,
            width: img.naturalWidth,
            height: img.naturalHeight,
          });
        reader.onerror = () => reject(new Error('FileReader failed'));
        reader.readAsDataURL(blob);
      } catch (e) {
        reject(e);
      }
    };
    img.onerror = () => reject(new Error('Image load failed'));
    img.src = url;
  });
}

/**
 * Draw a blue -> fuchsia gradient accent bar at the top of the current page.
 * jsPDF does not support true gradients, so we approximate by drawing a
 * sequence of thin rectangles with interpolated colors.
 */
function drawGradientBar(pdf: jsPDF, pageW: number) {
  const barH = 4;
  const steps = 80;
  const stepW = pageW / steps;
  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);
    const r = Math.round(BLUE.r + (FUCHSIA.r - BLUE.r) * t);
    const g = Math.round(BLUE.g + (FUCHSIA.g - BLUE.g) * t);
    const b = Math.round(BLUE.b + (FUCHSIA.b - BLUE.b) * t);
    pdf.setFillColor(r, g, b);
    // Overlap slightly to avoid faint seams between rects
    pdf.rect(i * stepW, 0, stepW + 0.2, barH, 'F');
  }
}

/** Draw a horizontal rule across the content area. */
function drawHR(pdf: jsPDF, y: number, marginL: number, marginR: number) {
  pdf.setDrawColor(LINE.r, LINE.g, LINE.b);
  pdf.setLineWidth(0.4);
  pdf.line(marginL, y, pdf.internal.pageSize.getWidth() - marginR, y);
}

/** Draw the "Generated by ... / Powered by MightyMail™" footer. */
function drawFooter(pdf: jsPDF, pageW: number, pageH: number, mR: number) {
  const footerY = pageH - 10;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  pdf.setTextColor(MUTED.r, MUTED.g, MUTED.b);
  pdf.text(`Generated by ${PLATFORM_LABEL}`, pageW / 2, footerY, {
    align: 'center',
  });

  pdf.setFont('helvetica', 'italic');
  pdf.setFontSize(7);
  pdf.setTextColor(LINE.r, LINE.g, LINE.b);
  pdf.text('Powered by MightyMail\u2122', pageW - mR, footerY, {
    align: 'right',
  });
}

/** Draw a blue bullet dot followed by wrapped text. Returns new y. */
function drawBullet(
  pdf: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight = 4.6
): number {
  // Blue dot
  pdf.setFillColor(BLUE.r, BLUE.g, BLUE.b);
  pdf.circle(x + 1.2, y - 1.3, 0.9, 'F');

  // Wrapped text, indented past the dot
  const textX = x + 4;
  const textW = maxWidth - 4;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(DARK.r, DARK.g, DARK.b);

  const lines = pdf.splitTextToSize(text, textW) as string[];
  for (const line of lines) {
    pdf.text(line, textX, y);
    y += lineHeight;
  }
  return y + 1;
}

/** Draw a uppercase bold blue section heading. Returns new y. */
function drawSectionHeading(
  pdf: jsPDF,
  text: string,
  x: number,
  y: number,
  size = 13
): number {
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(size);
  pdf.setTextColor(BLUE.r, BLUE.g, BLUE.b);
  pdf.text(text.toUpperCase(), x, y);
  return y + size * 0.45;
}

/** Draw a smaller bold dark subheading for a bullet group. Returns new y. */
function drawSubHeading(
  pdf: jsPDF,
  text: string,
  x: number,
  y: number
): number {
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.setTextColor(DARK.r, DARK.g, DARK.b);
  pdf.text(text, x, y);
  return y + 5;
}

/** Draw wrapped body paragraph. Returns new y. */
function drawParagraph(
  pdf: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight = 4.8
): number {
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(DARK.r, DARK.g, DARK.b);
  const lines = pdf.splitTextToSize(text, maxWidth) as string[];
  for (const line of lines) {
    pdf.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

// ── Main generator ──────────────────────────────────────────────────────

export async function generateWrapCarePDF(data: WrapCarePDFData): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'letter', // 215.9 x 279.4 mm
  });

  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const mL = 16;
  const mR = 16;
  const contentW = pageW - mL - mR;

  // Pre-load logo once (used on page 1)
  let logo: { dataUrl: string; width: number; height: number } | null = null;
  if (data.shopLogoUrl) {
    try {
      logo = await loadImageAsDataUrl(data.shopLogoUrl);
    } catch {
      logo = null;
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 1 — COVER / INTRO
  // ═══════════════════════════════════════════════════════════════════════

  drawGradientBar(pdf, pageW);

  let y = 40;

  // Logo (top-center, large)
  if (logo) {
    const maxH = 40;
    const maxW = 70;
    const scale = Math.min(maxW / logo.width, maxH / logo.height);
    const w = logo.width * scale;
    const h = logo.height * scale;
    const x = (pageW - w) / 2;
    pdf.addImage(logo.dataUrl, 'PNG', x, y, w, h);
    y += h + 8;
  } else {
    y += 10;
  }

  // Shop name — big bold
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(26);
  pdf.setTextColor(DARK.r, DARK.g, DARK.b);
  pdf.text(data.shopName, pageW / 2, y, { align: 'center' });
  y += 14;

  // Title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(22);
  pdf.setTextColor(BLUE.r, BLUE.g, BLUE.b);
  pdf.text('VEHICLE WRAP CARE GUIDE', pageW / 2, y, { align: 'center' });
  y += 8;

  // Subtitle
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(12);
  pdf.setTextColor(MUTED.r, MUTED.g, MUTED.b);
  pdf.text(
    'Everything you need to keep your wrap looking new',
    pageW / 2,
    y,
    { align: 'center' }
  );
  y += 14;

  // Fuchsia accent divider line
  pdf.setDrawColor(FUCHSIA.r, FUCHSIA.g, FUCHSIA.b);
  pdf.setLineWidth(0.8);
  const dividerW = 40;
  pdf.line(
    (pageW - dividerW) / 2,
    y,
    (pageW + dividerW) / 2,
    y
  );
  y += 14;

  // Customer info box
  const boxX = mL + 10;
  const boxW = contentW - 20;
  const boxPad = 6;

  // Build the info rows
  const vehicleStr =
    [data.vehicle?.year, data.vehicle?.make, data.vehicle?.model]
      .filter(Boolean)
      .join(' ') || 'Not specified';

  const installDateStr = data.installDate
    ? new Date(data.installDate).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : 'Not specified';

  const filmColorParts: string[] = [];
  if (data.colorName) filmColorParts.push(data.colorName);
  if (data.finish) filmColorParts.push(data.finish);
  const filmColorStr = filmColorParts.join(' / ') || 'Not specified';

  const infoRows: [string, string][] = [
    ['Customer', data.customerName || 'Not specified'],
    ['Vehicle', vehicleStr],
    ['Install Date', installDateStr],
    ['Film / Color', filmColorStr],
    ['Manufacturer', data.manufacturer || 'Not specified'],
  ];

  const rowH = 7;
  const boxH = boxPad * 2 + rowH * infoRows.length + 6;

  // Box background + border
  pdf.setFillColor(LIGHT.r, LIGHT.g, LIGHT.b);
  pdf.roundedRect(boxX, y, boxW, boxH, 2, 2, 'F');
  pdf.setDrawColor(LINE.r, LINE.g, LINE.b);
  pdf.setLineWidth(0.4);
  pdf.roundedRect(boxX, y, boxW, boxH, 2, 2, 'S');

  // Box header label
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(9);
  pdf.setTextColor(BLUE.r, BLUE.g, BLUE.b);
  pdf.text('INSTALL DETAILS', boxX + boxPad, y + boxPad + 2);

  let rowY = y + boxPad + 10;
  for (const [label, value] of infoRows) {
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.setTextColor(DARK.r, DARK.g, DARK.b);
    pdf.text(`${label}:`, boxX + boxPad, rowY);

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(DARK.r, DARK.g, DARK.b);
    const valueLines = pdf.splitTextToSize(
      value,
      boxW - boxPad * 2 - 35
    ) as string[];
    pdf.text(valueLines[0] || '', boxX + boxPad + 35, rowY);

    rowY += rowH;
  }

  drawFooter(pdf, pageW, pageH, mR);

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 2 — CARE INSTRUCTIONS
  // ═══════════════════════════════════════════════════════════════════════

  pdf.addPage();
  drawGradientBar(pdf, pageW);

  y = 20;

  // Section header
  y = drawSectionHeading(pdf, 'How to Care For Your Wrap', mL, y, 16);
  y += 4;

  // Fuchsia accent line under heading
  pdf.setDrawColor(FUCHSIA.r, FUCHSIA.g, FUCHSIA.b);
  pdf.setLineWidth(0.8);
  pdf.line(mL, y, mL + 30, y);
  y += 6;

  // Intro blurb
  y = drawParagraph(
    pdf,
    'Your vehicle wrap is a premium finish. Follow these guidelines to keep it looking its best for years to come.',
    mL,
    y,
    contentW
  );
  y += 4;

  // Care sections
  const careSections: { title: string; bullets: string[] }[] = [
    {
      title: 'First 48 Hours',
      bullets: [
        "Don't wash the vehicle — the adhesive is still setting.",
        "Don't drive through an automatic car wash.",
        'Avoid direct sun for extended periods if possible.',
        'Let the adhesive fully cure before any cleaning or contact.',
      ],
    },
    {
      title: 'Hand Washing (Recommended)',
      bullets: [
        'Use a pH-neutral automotive soap designed for vinyl or clear coats.',
        'Wash with a soft microfiber cloth or mitt — never abrasive sponges.',
        'Use warm (not hot) water and work in the shade when possible.',
        'Rinse thoroughly to remove all soap residue.',
        'Pat dry with a clean microfiber towel to prevent water spots.',
      ],
    },
    {
      title: 'What to Avoid',
      bullets: [
        'No automatic car washes with brushes — they can lift and scratch the film.',
        'No pressure washers above 2000 PSI, and never spray within 12 inches of the surface.',
        'No wax or polish containing petroleum, solvents, or abrasives.',
        'No abrasive cleaners, scouring pads, or rough towels.',
      ],
    },
    {
      title: 'Removing Stains',
      bullets: [
        'Address spills, bird droppings, and bug splatter immediately — the longer they sit, the harder they are to remove.',
        'For stubborn stains, use isopropyl alcohol diluted 50/50 with water and a soft cloth.',
        'NEVER use gasoline, brake cleaner, acetone, or other harsh chemicals — they will permanently damage the film.',
      ],
    },
    {
      title: 'Parking & Storage',
      bullets: [
        'Avoid prolonged direct sunlight — UV exposure is the #1 cause of wrap fade.',
        'Park in the shade or inside a garage whenever possible.',
        'If stored outdoors long-term, use a breathable vehicle cover.',
      ],
    },
    {
      title: 'Fuel & Chemical Spills',
      bullets: [
        'Wipe fuel, oil, and chemical spills immediately with a clean cloth.',
        'Rinse the area with water right after wiping.',
        "Don't let any spill sit on the wrap — prolonged contact will stain or degrade the film.",
      ],
    },
    {
      title: 'Winter Care',
      bullets: [
        'Rinse road salt off regularly to prevent buildup and edge lifting.',
        'Avoid parking on heated driveways, which can soften the adhesive and cause lifting.',
      ],
    },
  ];

  for (const section of careSections) {
    // Estimate block height to decide if we need a new page
    let estH = 7; // subheading
    for (const b of section.bullets) {
      const lines = pdf.splitTextToSize(b, contentW - 4) as string[];
      estH += lines.length * 4.6 + 1;
    }
    estH += 3;

    if (y + estH > pageH - 18) {
      drawFooter(pdf, pageW, pageH, mR);
      pdf.addPage();
      drawGradientBar(pdf, pageW);
      y = 20;
    }

    y = drawSubHeading(pdf, section.title, mL, y);
    for (const bullet of section.bullets) {
      y = drawBullet(pdf, bullet, mL, y, contentW);
    }
    y += 3;
  }

  drawFooter(pdf, pageW, pageH, mR);

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 3 — WARRANTY & CONTACT
  // ═══════════════════════════════════════════════════════════════════════

  pdf.addPage();
  drawGradientBar(pdf, pageW);

  y = 20;

  // YOUR WRAP'S LIFESPAN
  y = drawSectionHeading(pdf, "Your Wrap's Lifespan", mL, y, 14);
  y += 4;
  pdf.setDrawColor(FUCHSIA.r, FUCHSIA.g, FUCHSIA.b);
  pdf.setLineWidth(0.8);
  pdf.line(mL, y, mL + 30, y);
  y += 6;

  y = drawParagraph(
    pdf,
    'With proper care, your wrap will maintain its appearance for 5-7 years. Most manufacturers offer warranties of 3-10 years depending on finish and application.',
    mL,
    y,
    contentW
  );
  y += 8;

  drawHR(pdf, y, mL, mR);
  y += 8;

  // MANUFACTURER WARRANTY
  y = drawSectionHeading(pdf, 'Manufacturer Warranty', mL, y, 14);
  y += 4;
  pdf.setDrawColor(FUCHSIA.r, FUCHSIA.g, FUCHSIA.b);
  pdf.setLineWidth(0.8);
  pdf.line(mL, y, mL + 30, y);
  y += 6;

  const manufacturerLabel = data.manufacturer || 'manufacturer';
  y = drawParagraph(
    pdf,
    `Your wrap is covered by the ${manufacturerLabel} warranty for defects in materials and workmanship. Normal wear and tear, damage from improper cleaning, or damage from accidents is not covered.`,
    mL,
    y,
    contentW
  );
  y += 8;

  drawHR(pdf, y, mL, mR);
  y += 8;

  // QUESTIONS OR ISSUES?
  y = drawSectionHeading(pdf, 'Questions or Issues?', mL, y, 14);
  y += 4;
  pdf.setDrawColor(FUCHSIA.r, FUCHSIA.g, FUCHSIA.b);
  pdf.setLineWidth(0.8);
  pdf.line(mL, y, mL + 30, y);
  y += 6;

  y = drawParagraph(
    pdf,
    "If you have any questions about caring for your wrap, notice any issues, or need a repair, please reach out — we're here to help.",
    mL,
    y,
    contentW
  );
  y += 4;

  // Contact card
  const contactBoxX = mL;
  const contactBoxY = y;
  const contactBoxW = contentW;
  const contactRows: [string, string][] = [];
  contactRows.push(['Shop', data.shopName]);
  if (data.shopPhone) contactRows.push(['Phone', data.shopPhone]);
  if (data.shopEmail) contactRows.push(['Email', data.shopEmail]);
  if (data.shopWebsite) contactRows.push(['Website', data.shopWebsite]);

  const contactRowH = 7;
  const contactBoxH = 8 + contactRows.length * contactRowH + 4;

  pdf.setFillColor(LIGHT.r, LIGHT.g, LIGHT.b);
  pdf.roundedRect(contactBoxX, contactBoxY, contactBoxW, contactBoxH, 2, 2, 'F');
  pdf.setDrawColor(LINE.r, LINE.g, LINE.b);
  pdf.setLineWidth(0.4);
  pdf.roundedRect(contactBoxX, contactBoxY, contactBoxW, contactBoxH, 2, 2, 'S');

  let cRowY = contactBoxY + 9;
  for (const [label, value] of contactRows) {
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.setTextColor(BLUE.r, BLUE.g, BLUE.b);
    pdf.text(`${label}:`, contactBoxX + 6, cRowY);

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(DARK.r, DARK.g, DARK.b);
    const valueLines = pdf.splitTextToSize(
      value,
      contactBoxW - 12 - 28
    ) as string[];
    pdf.text(valueLines[0] || '', contactBoxX + 6 + 28, cRowY);

    cRowY += contactRowH;
  }

  y = contactBoxY + contactBoxH + 10;

  // Thank-you line near the bottom
  if (y < pageH - 30) {
    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(11);
    pdf.setTextColor(MUTED.r, MUTED.g, MUTED.b);
    pdf.text(
      'Thank you for trusting us with your vehicle.',
      pageW / 2,
      pageH - 22,
      { align: 'center' }
    );
  }

  drawFooter(pdf, pageW, pageH, mR);

  // ─── SAVE ───────────────────────────────────────────────────────────

  const safeShop = data.shopName.replace(/[^a-zA-Z0-9]/g, '-').substring(0, 30);
  const customerOrVehicle =
    data.customerName ||
    [data.vehicle?.year, data.vehicle?.make, data.vehicle?.model]
      .filter(Boolean)
      .join(' ') ||
    'Client';
  const safeTarget = customerOrVehicle
    .replace(/[^a-zA-Z0-9]/g, '-')
    .substring(0, 30);
  const filename = `WrapCare-${safeShop}-${safeTarget}.pdf`;
  pdf.save(filename);
}
