/**
 * WallPro Seeded Design Gallery — 60 designs across 6 categories
 * Each design stores a Gemini prompt for future AI generation.
 *
 * Batch 2 (48+) is tuned to the new generate-wall-design prompt engineering:
 * Williams Sonoma / Restoration Hardware / Schumacher caliber, with tangible
 * depth and texture (paper grain, brush stroke, stone, woven fiber, metallic
 * leaf, ink bleed), typography/branding support, and photorealistic fidelity.
 */

export interface WallDesign {
  id: string;
  category: string;
  name: string;
  description: string;
  prompt: string;
  thumbGradient: string;
}

export const CATEGORIES = [
  "Luxury Residential",
  "Fitness & Gym",
  "Retail & Showroom",
  "Corporate & Office",
  "Restaurant & Hospitality",
  "Automotive & Garage",
] as const;

export const WALL_DESIGNS: WallDesign[] = [
  // ── Luxury Residential ──────────────────────────────────────
  { id: "lr-1", category: "Luxury Residential", name: "Dark Botanical Garden", description: "Dramatic oversized florals on deep black \u2014 Dutch Masters inspired", prompt: "Dramatic dark moody botanical wall mural with oversized roses peonies dahlias in deep burgundy blush pink and cream on near-black background, Dutch Masters painting style, seamless wallpaper design, ultra high resolution print-ready", thumbGradient: "linear-gradient(160deg, #1a0a10 0%, #2d1520 35%, #1a0d12 65%, #0d0d0d 100%)" },
  { id: "lr-2", category: "Luxury Residential", name: "Italian Marble Luxe", description: "Calacatta gold marble with warm dramatic veining", prompt: "Seamless Calacatta gold marble wall surface with dramatic white stone and warm gold veining, polished finish, photorealistic luxury interior texture, print-ready 8K resolution", thumbGradient: "linear-gradient(135deg, #f5f0e8 0%, #e8ddd0 30%, #f2ece3 65%, #d4c5b0 100%)" },
  { id: "lr-3", category: "Luxury Residential", name: "Art Deco Gold", description: "Geometric fan patterns in black and brushed gold", prompt: "Elegant art deco geometric pattern with symmetrical fan shapes and chevrons in matte black and brushed gold, luxury wallpaper design, seamless repeating, sophisticated 1920s inspired, print-ready", thumbGradient: "linear-gradient(145deg, #0d0d0d 0%, #1a1812 40%, #0d0b08 70%, #1a1a1a 100%)" },
  { id: "lr-4", category: "Luxury Residential", name: "Tropical Palm Paradise", description: "Lush palm fronds and monstera on deep emerald", prompt: "Lush tropical palm fronds and monstera leaves on deep emerald green background, botanical illustration style, luxury wallpaper mural, hand-painted aesthetic, rich saturated greens, print-ready seamless", thumbGradient: "linear-gradient(150deg, #0a2e1a 0%, #1a4a2e 45%, #0d3d1f 75%, #082010 100%)" },
  { id: "lr-5", category: "Luxury Residential", name: "Abstract Watercolor Blush", description: "Soft flowing watercolor washes in blush and warm gray", prompt: "Abstract watercolor wall mural in soft blush pink warm gray and ivory, flowing organic washes and gentle color bleeding, feminine luxury interior design, seamless print-ready", thumbGradient: "linear-gradient(135deg, #f5e6e0 0%, #e8d5ce 35%, #f0e0d8 60%, #ddc8be 100%)" },
  { id: "lr-6", category: "Luxury Residential", name: "Venetian Plaster Texture", description: "Rich textured plaster surface in warm taupe", prompt: "Venetian plaster wall texture in warm taupe and cream with subtle depth variation and natural imperfections, luxury Mediterranean interior finish, photorealistic seamless print-ready", thumbGradient: "linear-gradient(140deg, #c4b5a0 0%, #b8a890 40%, #d1c2ad 70%, #a89880 100%)" },
  { id: "lr-7", category: "Luxury Residential", name: "Foyer Limewash Plaster", description: "Hand-troweled limewash in warm camel with dimensional depth", prompt: "Hand-troweled limewash plaster wall in warm camel and soft terracotta, dimensional trowel marks and natural cloudy tonal variation, tactile surface texture, luxury foyer feature wall, Schumacher caliber, photorealistic print-ready seamless", thumbGradient: "linear-gradient(140deg, #d4b598 0%, #c29d7a 40%, #e0c2a0 70%, #b08c68 100%)" },
  { id: "lr-8", category: "Luxury Residential", name: "Powder Room Chinoiserie", description: "Hand-painted silk chinoiserie peonies and cranes", prompt: "Hand-painted silk-style chinoiserie wallpaper with dimensional peonies, plum blossoms, bamboo, and cranes on pale duck-egg blue ground, fine brushwork and gold-leaf accents, De Gournay aesthetic, powder room feature, photorealistic print-ready seamless", thumbGradient: "linear-gradient(135deg, #c5d9de 0%, #a8c3cb 30%, #d4e3e6 55%, #b0cad2 80%, #c0d5da 100%)" },
  { id: "lr-9", category: "Luxury Residential", name: "Dining Room Raised Damask", description: "Dimensional embossed damask in champagne and ivory", prompt: "Dimensional raised damask wallpaper with embossed tonal medallion pattern in champagne and ivory, subtle metallic sheen and tactile velvet flocking, formal dining room feature wall, Fromental caliber, photorealistic print-ready seamless", thumbGradient: "linear-gradient(135deg, #eadfc8 0%, #d8c8a8 40%, #f0e6d0 70%, #c8b890 100%)" },
  { id: "lr-10", category: "Luxury Residential", name: "Library Leather Books", description: "Trompe l'oeil leather-bound library shelves floor-to-ceiling", prompt: "Trompe l'oeil leather-bound antique library shelves wall mural floor to ceiling, richly varied book spines in oxblood burgundy forest green and tan with embossed gold leaf lettering on spines, dusty patina, photorealistic depth, study feature wall, print-ready seamless", thumbGradient: "linear-gradient(160deg, #2a1a15 0%, #4a2820 30%, #3a2015 55%, #5a3025 80%, #2a1812 100%)" },
  { id: "lr-11", category: "Luxury Residential", name: "Nursery Soft Moon & Stars", description: "Watercolor moon, stars, and drifting clouds in dusty blue", prompt: "Tender hand-painted watercolor moon stars and drifting clouds on soft dusty-blue ground with gentle gradient sky, whisper-fine gold-leaf star accents, gender-neutral nursery mural, Anthropologie caliber, photorealistic paper-grain texture, print-ready seamless", thumbGradient: "linear-gradient(180deg, #a8c2da 0%, #c8d8ea 35%, #90b0cc 60%, #b8d0e2 85%, #a0bcd2 100%)" },
  { id: "lr-12", category: "Luxury Residential", name: "Kitchen Herbal Botanical", description: "Hand-inked kitchen herbs on warm off-white linen", prompt: "Hand-inked vintage botanical wallpaper of kitchen herbs rosemary thyme sage basil and lavender on warm off-white linen-textured ground, fine cross-hatched illustration style, botanical plate aesthetic, kitchen accent wall, photorealistic print-ready seamless", thumbGradient: "linear-gradient(145deg, #efe8d5 0%, #d8d0b8 35%, #3d5530 55%, #e5ddc8 75%, #f2ecdc 100%)" },

  // ── Fitness & Gym ───────────────────────────────────────────
  { id: "fg-1", category: "Fitness & Gym", name: "Industrial Grit", description: "Dark concrete and steel with raw urban texture", prompt: "Dark industrial concrete wall texture with exposed steel elements and subtle grunge overlay, gym interior mural, raw urban aesthetic, charcoal and steel gray, matte finish print-ready", thumbGradient: "linear-gradient(145deg, #1a1a1a 0%, #2a2a2a 40%, #1f1f1f 70%, #252525 100%)" },
  { id: "fg-2", category: "Fitness & Gym", name: "Geometric Power", description: "Bold angular shapes in deep blue and charcoal", prompt: "Bold geometric abstract wall mural with sharp angular shapes in deep navy blue and charcoal gray on matte black background, athletic modern design, gym interior, print-ready seamless", thumbGradient: "linear-gradient(160deg, #0a0a0a 0%, #0d1f33 45%, #111827 75%, #0a0a0a 100%)" },
  { id: "fg-3", category: "Fitness & Gym", name: "Concrete Motivation", description: "Raw concrete with subtle typographic texture", prompt: "Raw exposed concrete wall texture with subtle embossed motivational typography pattern, industrial gym aesthetic, gray tones, matte finish, print-ready seamless", thumbGradient: "linear-gradient(135deg, #3a3a3a 0%, #4a4a4a 35%, #353535 65%, #404040 100%)" },
  { id: "fg-4", category: "Fitness & Gym", name: "Dark Athletic Camo", description: "Modern camouflage pattern in dark grays and black", prompt: "Modern geometric camouflage pattern in dark charcoal gray and black tones, athletic military inspired, gym wall mural, matte finish, print-ready seamless", thumbGradient: "linear-gradient(150deg, #1a1a1a 0%, #2d2d2d 30%, #1f1f1f 55%, #333333 80%, #1a1a1a 100%)" },
  { id: "fg-5", category: "Fitness & Gym", name: "Iron Texture", description: "Weathered brushed iron surface with patina", prompt: "Weathered brushed iron metal wall texture with subtle rust patina and industrial character, dark metallic gym interior surface, photorealistic print-ready seamless", thumbGradient: "linear-gradient(140deg, #2a2520 0%, #3d3530 40%, #2f2825 70%, #352e28 100%)" },
  { id: "fg-6", category: "Fitness & Gym", name: "Dynamic Lines", description: "Flowing speed lines in gray gradient on black", prompt: "Dynamic flowing speed lines and motion streaks in silver gray gradient on matte black background, athletic energy movement graphic, gym wall mural, print-ready seamless", thumbGradient: "linear-gradient(170deg, #0a0a0a 0%, #1a1a1a 30%, #2a2a2a 50%, #0d0d0d 80%, #1a1a1a 100%)" },

  // ── Retail & Showroom ───────────────────────────────────────
  { id: "rs-1", category: "Retail & Showroom", name: "Brand Gradient Wall", description: "Smooth gradient wash \u2014 customizable to any brand palette", prompt: "Smooth flowing color gradient wall mural transitioning from deep navy to soft sky blue, subtle texture overlay, modern retail interior backdrop, clean professional, print-ready seamless", thumbGradient: "linear-gradient(135deg, #0c1e3a 0%, #1a3a5c 40%, #2a5a8c 70%, #4a8ab8 100%)" },
  { id: "rs-2", category: "Retail & Showroom", name: "Minimalist Line Art", description: "Delicate continuous line drawings on warm white", prompt: "Minimalist continuous line art illustration on warm white background, delicate botanical and abstract shapes, thin black ink lines, modern retail gallery aesthetic, print-ready seamless", thumbGradient: "linear-gradient(135deg, #faf8f5 0%, #f2efe8 40%, #f8f5f0 70%, #ede8e0 100%)" },
  { id: "rs-3", category: "Retail & Showroom", name: "Bold Type Statement", description: "Large-scale typography graphic in black and white", prompt: "Large-scale bold typographic wall mural with overlapping letter forms in black on white, modern graphic design aesthetic, editorial retail interior, print-ready", thumbGradient: "linear-gradient(155deg, #f5f5f5 0%, #e0e0e0 25%, #1a1a1a 50%, #333333 75%, #f0f0f0 100%)" },
  { id: "rs-4", category: "Retail & Showroom", name: "Luxury Texture Panel", description: "Rich leather-like textured surface in deep cognac", prompt: "Rich leather-like textured wall surface in deep cognac brown with subtle grain and warmth, luxury retail interior, photorealistic print-ready seamless", thumbGradient: "linear-gradient(140deg, #4a2c1a 0%, #6b3d22 40%, #5a3320 70%, #3d2215 100%)" },
  { id: "rs-5", category: "Retail & Showroom", name: "Terrazzo Modern", description: "Contemporary terrazzo pattern in muted earth tones", prompt: "Contemporary terrazzo pattern wall surface with organic stone chips in muted earth tones cream sand gray and terracotta on warm white base, modern retail interior, print-ready seamless", thumbGradient: "linear-gradient(135deg, #f0e8dd 0%, #e5d8c8 30%, #ddd0c0 55%, #e8ddd0 80%, #f2ece3 100%)" },
  { id: "rs-6", category: "Retail & Showroom", name: "Lifestyle Mural", description: "Aspirational lifestyle photography composite", prompt: "Aspirational lifestyle wall mural composite with warm golden hour photography aesthetic, travel and nature imagery blend, modern retail inspiration wall, warm tones, print-ready", thumbGradient: "linear-gradient(145deg, #c4a060 0%, #d4b070 35%, #a88845 65%, #c0984a 100%)" },
  { id: "rs-7", category: "Retail & Showroom", name: "Flagship Logo Plaster", description: "Oversized brushed-brass wordmark on warm terracotta plaster", prompt: "Flagship retail feature wall with oversized custom brushed-brass wordmark logo mounted over warm terracotta limewash plaster, dimensional cast shadow behind letterforms, tactile hand-troveled plaster texture with tonal cloud variation, environmental branding wall, Aesop caliber, photorealistic print-ready", thumbGradient: "linear-gradient(140deg, #c88860 0%, #b27046 35%, #d4987a 65%, #a86438 100%)" },
  { id: "rs-8", category: "Retail & Showroom", name: "Boutique Pastel Terrazzo", description: "Oversized terrazzo in blush, peach, cream, and bone", prompt: "Oversized contemporary terrazzo wall surface with organic stone chips in blush pink peach cream and bone on warm ivory base, dimensional poured-stone texture with subtle depth, modern boutique retail interior, Ganni caliber, photorealistic print-ready seamless", thumbGradient: "linear-gradient(135deg, #f5e8dc 0%, #ebd0c0 30%, #f8e0d0 55%, #ddc5b0 80%, #f2dccc 100%)" },
  { id: "rs-9", category: "Retail & Showroom", name: "Tasting Room Vineyard", description: "Hand-illustrated vineyard landscape in moody charcoal ink", prompt: "Hand-illustrated vineyard landscape wall mural with rolling terraced vines, cypress trees, and distant stone farmhouse in moody charcoal ink and burnt-sienna wash on warm cream paper ground, fine cross-hatched editorial illustration style, wine-tasting room feature wall, photorealistic print-ready", thumbGradient: "linear-gradient(170deg, #d8ccb5 0%, #3a3a2f 30%, #8a6a48 55%, #4a4030 80%, #c0b498 100%)" },
  { id: "rs-10", category: "Retail & Showroom", name: "Pop-Up Duotone Graphic", description: "High-contrast duotone photography in magenta and cobalt", prompt: "High-contrast editorial duotone photography wall mural in magenta and cobalt blue, graphic pop-culture portraiture style, full-bleed large-format retail pop-up feature wall, bold saturated print impact, photorealistic high fidelity, print-ready", thumbGradient: "linear-gradient(135deg, #d81a6b 0%, #8a1550 35%, #1a3a9a 65%, #0c1f6a 100%)" },
  { id: "rs-11", category: "Retail & Showroom", name: "Beauty Counter Soft Arch", description: "Moroccan plaster arch with dimensional shadow and soft gradient", prompt: "Plaster Moroccan arch motif wall design with dimensional recessed shadow and soft blush-to-peach gradient field inside the arch, tactile limewash plaster surround in warm bone, minimalist beauty counter feature wall, Rhode caliber, photorealistic print-ready", thumbGradient: "linear-gradient(160deg, #e8d5c5 0%, #f2dccc 35%, #d8b5a0 60%, #ecd8c5 85%, #e0c8b5 100%)" },
  { id: "rs-12", category: "Retail & Showroom", name: "Denim Brand Manifesto", description: "Editorial manifesto typography on brushed denim linen", prompt: "Editorial brand-manifesto typography wall mural with custom serif display headline and manifesto body copy, crisp letterforms, set over brushed denim-textured linen ground in indigo, environmental branding, flagship denim retail feature wall, vector-sharp typography, photorealistic print-ready", thumbGradient: "linear-gradient(145deg, #1a2d50 0%, #2a4270 35%, #0f1f3a 65%, #253858 100%)" },

  // ── Corporate & Office ──────────────────────────────────────
  { id: "co-1", category: "Corporate & Office", name: "Subtle Linen", description: "Clean woven linen texture in light warm gray", prompt: "Clean woven linen fabric wall texture in light warm gray with subtle weave pattern, professional office interior, minimal elegant, photorealistic print-ready seamless", thumbGradient: "linear-gradient(135deg, #e8e4de 0%, #ddd8d0 40%, #e5e0d8 70%, #d8d2c8 100%)" },
  { id: "co-2", category: "Corporate & Office", name: "Geometric Professional", description: "Clean geometric pattern in navy and silver", prompt: "Clean geometric hexagonal pattern in navy blue and silver gray, professional corporate office wall design, modern minimal, print-ready seamless", thumbGradient: "linear-gradient(150deg, #1a2840 0%, #2a3a55 40%, #1f3048 70%, #253650 100%)" },
  { id: "co-3", category: "Corporate & Office", name: "Cityscape Panoramic", description: "Monochrome city skyline in soft gray tones", prompt: "Monochrome city skyline panoramic wall mural in soft gray tones, architectural detail, modern office feature wall, professional atmosphere, print-ready", thumbGradient: "linear-gradient(180deg, #c8c8c8 0%, #a0a0a0 40%, #808080 65%, #606060 100%)" },
  { id: "co-4", category: "Corporate & Office", name: "Abstract Blue Flow", description: "Flowing abstract forms in corporate blue palette", prompt: "Flowing abstract organic forms in corporate blue palette from navy to sky blue with white accents, professional office feature wall, calming modern, print-ready seamless", thumbGradient: "linear-gradient(135deg, #0a1628 0%, #1a3050 35%, #2a5080 65%, #4080b0 100%)" },
  { id: "co-5", category: "Corporate & Office", name: "Warm Wood Grain", description: "Natural oak wood grain texture \u2014 warm and inviting", prompt: "Natural white oak wood grain wall texture with warm honey tones and natural knot character, professional warm office interior, photorealistic print-ready seamless", thumbGradient: "linear-gradient(175deg, #c4a47a 0%, #b8965e 35%, #d0b080 65%, #a88850 100%)" },
  { id: "co-6", category: "Corporate & Office", name: "Mission Feature", description: "Bold dark feature wall with subtle texture depth", prompt: "Deep charcoal matte wall surface with subtle brushed texture and depth variation, bold corporate feature wall, dramatic professional interior, print-ready seamless", thumbGradient: "linear-gradient(140deg, #1a1a1a 0%, #252525 40%, #1f1f1f 70%, #2a2a2a 100%)" },
  { id: "co-7", category: "Corporate & Office", name: "Values Wall Typography", description: "Monumental editorial brand-values type on warm concrete", prompt: "Monumental editorial brand-values typography wall mural with large custom serif display headline VALUES and supporting manifesto body copy set in refined neo-grotesque, crisp vector-sharp letterforms correctly spelled, set over warm smoothed concrete with subtle tonal variation, corporate HQ feature wall, environmental branding, photorealistic print-ready", thumbGradient: "linear-gradient(140deg, #cbc3b7 0%, #b8ae9e 35%, #d4ccc0 65%, #a89e8e 100%)" },
  { id: "co-8", category: "Corporate & Office", name: "Lobby Calacatta Viola", description: "Book-matched Calacatta Viola marble lobby statement", prompt: "Book-matched Calacatta Viola marble lobby feature wall with dramatic symmetrical veining in deep plum and rust over creamy white stone, polished honed finish, mirror-matched slab pairing, luxury corporate lobby, photorealistic ultra high-resolution print-ready seamless", thumbGradient: "linear-gradient(135deg, #e8dcd0 0%, #6a3240 25%, #f0e4d8 45%, #8a4a38 65%, #eddfd2 85%, #502838 100%)" },
  { id: "co-9", category: "Corporate & Office", name: "Conference Topography", description: "Subtle topographical contour map in two tones of putty", prompt: "Subtle topographical contour line map wall design in two tones of warm putty over linen ground, thin dimensional ridge lines with soft shadow, conference room feature wall, quiet sophisticated corporate aesthetic, photorealistic print-ready seamless", thumbGradient: "linear-gradient(145deg, #d8cfbd 0%, #c4ba9f 35%, #e0d7c5 65%, #b8ae92 100%)" },
  { id: "co-10", category: "Corporate & Office", name: "Mission Statement Script", description: "Hand-lettered mission statement in refined script on linen", prompt: "Hand-lettered brand mission statement in refined custom calligraphic script with subtle ink bleed character, set over natural Belgian linen ground with visible fiber weave, framed as anchored headline with elegant hierarchy, environmental branding wall, correctly spelled, photorealistic print-ready", thumbGradient: "linear-gradient(140deg, #e8dfc8 0%, #d4caaf 35%, #ecdfc8 70%, #c8bea0 100%)" },
  { id: "co-11", category: "Corporate & Office", name: "Wayfinding Directory", description: "Editorial wayfinding directory typography in charcoal and brass", prompt: "Editorial wayfinding directory wall with organized typographic hierarchy listing floor names departments and suite numbers in crisp neo-grotesque type, deep charcoal on warm bone-linen ground with brushed-brass rule lines and floor icons, correctly spelled vector-sharp letterforms, corporate lobby wayfinding, photorealistic print-ready", thumbGradient: "linear-gradient(145deg, #e0d8c8 0%, #1f1f1f 30%, #c8a060 50%, #e8e0d0 70%, #2a2a2a 95%)" },
  { id: "co-12", category: "Corporate & Office", name: "Donor Wall Embossed Linen", description: "Embossed donor names on natural Belgian linen", prompt: "Embossed donor recognition wall with organized typographic hierarchy of individual donor names in tone-on-tone relief on natural Belgian linen ground, subtle dimensional letterpress depth and soft shadow, grouped by giving tier, environmental branding for hospital university or museum lobby, correctly spelled vector-sharp letterforms, photorealistic print-ready", thumbGradient: "linear-gradient(145deg, #e8dfc8 0%, #d8cfb5 35%, #ede4ce 65%, #c8bea0 100%)" },

  // ── Restaurant & Hospitality ────────────────────────────────
  { id: "rh-1", category: "Restaurant & Hospitality", name: "Moody Wine & Dine", description: "Deep burgundy and black with subtle damask texture", prompt: "Deep burgundy and black wall surface with subtle damask pattern overlay, moody upscale restaurant interior, rich warm atmosphere, print-ready seamless", thumbGradient: "linear-gradient(145deg, #2a0a10 0%, #3d1520 40%, #1a0810 70%, #2d1018 100%)" },
  { id: "rh-2", category: "Restaurant & Hospitality", name: "Fresh Farm Botanical", description: "Hand-drawn herbs and botanicals on cream", prompt: "Hand-drawn botanical illustration of kitchen herbs and garden plants on warm cream background, rustic farm-to-table restaurant aesthetic, vintage ink style, print-ready seamless", thumbGradient: "linear-gradient(135deg, #f5f0e5 0%, #e8e0d0 35%, #2a4a2a 50%, #e0d8c5 65%, #f0e8d8 100%)" },
  { id: "rh-3", category: "Restaurant & Hospitality", name: "Industrial Brick", description: "Exposed red brick wall with aged character", prompt: "Exposed red brick wall texture with aged mortar and authentic weathering, industrial restaurant interior, warm rustic character, photorealistic print-ready seamless", thumbGradient: "linear-gradient(140deg, #6b3a2a 0%, #8b4a32 35%, #5a3025 65%, #7a4030 100%)" },
  { id: "rh-4", category: "Restaurant & Hospitality", name: "Ocean Coastal", description: "Soft blue watercolor waves and coastal atmosphere", prompt: "Soft blue watercolor ocean waves wall mural with coastal atmosphere, gentle seafoam and sandy tones, beach restaurant interior, calming serene, print-ready seamless", thumbGradient: "linear-gradient(170deg, #a0c8d8 0%, #7ab0c8 35%, #c8dce0 55%, #90bcd0 80%, #d0e4e8 100%)" },
  { id: "rh-5", category: "Restaurant & Hospitality", name: "Warm Copper & Wood", description: "Brushed copper and dark walnut material blend", prompt: "Brushed copper metallic and dark walnut wood material blend wall texture, warm industrial gastro pub aesthetic, rich warm tones, print-ready seamless", thumbGradient: "linear-gradient(150deg, #3a2215 0%, #8a5a30 35%, #c08040 55%, #4a2a18 80%, #6a3820 100%)" },
  { id: "rh-6", category: "Restaurant & Hospitality", name: "Mediterranean Tile", description: "Hand-painted tile pattern in blue and white", prompt: "Hand-painted Mediterranean ceramic tile pattern in cobalt blue and white with subtle imperfections, traditional Moroccan Portuguese inspired, restaurant interior wall, print-ready seamless", thumbGradient: "linear-gradient(135deg, #f0f0f5 0%, #1a3a6a 25%, #f5f5fa 50%, #2a4a7a 75%, #f0f0f5 100%)" },
  { id: "rh-7", category: "Restaurant & Hospitality", name: "Hotel Lobby Magnolias", description: "Oversized hand-painted magnolias in taupe and blush", prompt: "Oversized hand-painted magnolia blooms and branches wall mural in soft taupe blush and cream with fine brushwork and subtle gold-leaf accents, dimensional petal shading, painterly paper-grain texture, luxury boutique hotel lobby feature wall, De Gournay caliber, photorealistic print-ready", thumbGradient: "linear-gradient(140deg, #e8dccc 0%, #d8c2b0 35%, #ecd8c8 60%, #c8a898 85%, #e0c8b5 100%)" },
  { id: "rh-8", category: "Restaurant & Hospitality", name: "Speakeasy Green Velvet Damask", description: "Emerald velvet with tonal gold damask", prompt: "Rich emerald green velvet textured wall with tonal antique-gold damask medallion pattern, dimensional flocked velvet pile with soft directional sheen, moody speakeasy cocktail bar feature wall, tactile luxurious depth, photorealistic print-ready seamless", thumbGradient: "linear-gradient(145deg, #0f3a28 0%, #1a5a3a 35%, #0a2a1c 65%, #245a38 100%)" },
  { id: "rh-9", category: "Restaurant & Hospitality", name: "Cafe Espresso Menu Type", description: "Hand-lettered menu typography on espresso plaster", prompt: "Hand-lettered editorial cafe menu typography wall with organized drink and pastry listings in custom script and neo-grotesque hierarchy, crisp correctly spelled vector-sharp letterforms set in warm cream chalk on espresso-brown limewash plaster with tactile trowel texture, environmental branding for specialty coffee shop, photorealistic print-ready", thumbGradient: "linear-gradient(145deg, #3a2418 0%, #4a2f22 35%, #2f1e14 65%, #523a2a 100%)" },
  { id: "rh-10", category: "Restaurant & Hospitality", name: "Rooftop Sunset Gradient", description: "Painted sunset in warm peach, gold, and dusty rose", prompt: "Painted gradient sunset wall mural with soft bands of warm peach gold and dusty rose blending into a deep plum horizon, brush-visible painterly texture with subtle canvas grain, dimensional atmospheric depth, rooftop bar feature wall, photorealistic print-ready", thumbGradient: "linear-gradient(180deg, #3d2850 0%, #8a4860 25%, #d88870 50%, #e8a868 75%, #f0c084 100%)" },
  { id: "rh-11", category: "Restaurant & Hospitality", name: "Steakhouse Saddle Leather", description: "Stitched saddle leather with brass nailhead detail", prompt: "Stitched saddle leather wall panel in warm cognac with hand-sewn welt seams and aged brass nailhead trim in regular pattern, rich dimensional leather grain and subtle patina, photorealistic tactile material depth, classic steakhouse booth-surround feature wall, print-ready seamless", thumbGradient: "linear-gradient(145deg, #5a3520 0%, #7a4a2c 30%, #4a2a18 55%, #8a5832 80%, #5e3620 100%)" },
  { id: "rh-12", category: "Restaurant & Hospitality", name: "Coastal Resort Watercolor", description: "Hand-painted tropical scene in airy watercolor", prompt: "Hand-painted airy watercolor tropical coastal scene wall mural with palms turquoise water and pale coral sky, loose brushwork with ink bleed and paper grain, dimensional atmospheric haze, luxury beach resort lobby feature wall, photorealistic print-ready", thumbGradient: "linear-gradient(180deg, #f2d8c5 0%, #e8bfa8 30%, #8ac5c8 55%, #5a9ab0 80%, #a8d2d5 100%)" },

  // ── Automotive & Garage ─────────────────────────────────────
  { id: "ag-1", category: "Automotive & Garage", name: "Racing Stripe Heritage", description: "Classic racing stripes in vintage motorsport colors", prompt: "Classic wide racing stripe wall graphic in vintage Le Mans blue and orange on matte dark gray, heritage motorsport aesthetic, garage wall mural, print-ready", thumbGradient: "linear-gradient(180deg, #2a2a2a 0%, #2a2a2a 35%, #1a3a6a 45%, #f08030 55%, #2a2a2a 65%, #2a2a2a 100%)" },
  { id: "ag-2", category: "Automotive & Garage", name: "Carbon Fiber", description: "Photorealistic carbon fiber weave in dark graphite", prompt: "Photorealistic carbon fiber weave wall texture in dark graphite with subtle reflective sheen, automotive garage interior, premium material surface, print-ready seamless", thumbGradient: "linear-gradient(135deg, #1a1a1a 0%, #2a2a2a 25%, #1f1f1f 50%, #2d2d2d 75%, #1a1a1a 100%)" },
  { id: "ag-3", category: "Automotive & Garage", name: "Garage Livery", description: "Motorsport team livery graphic in black and gray", prompt: "Motorsport team livery graphic pattern with angular geometric shapes in matte black and dark gray, racing aesthetic garage wall mural, bold automotive design, print-ready", thumbGradient: "linear-gradient(160deg, #0d0d0d 0%, #1a1a1a 30%, #333333 50%, #1a1a1a 70%, #0d0d0d 100%)" },
  { id: "ag-4", category: "Automotive & Garage", name: "Vintage Motorsport", description: "Aged vintage racing poster aesthetic in sepia tones", prompt: "Vintage motorsport poster aesthetic wall mural with aged sepia tones and classic race car silhouettes, retro automotive garage decor, distressed print texture, print-ready", thumbGradient: "linear-gradient(145deg, #4a3a28 0%, #6a5038 35%, #5a4030 65%, #3d2e20 100%)" },
  { id: "ag-5", category: "Automotive & Garage", name: "Checkered Graphic", description: "Deconstructed checkered flag in black and dark gray", prompt: "Deconstructed checkered flag graphic with fading dissolving squares in black and dark charcoal gray, modern automotive garage wall design, bold graphic, print-ready", thumbGradient: "linear-gradient(135deg, #0a0a0a 0%, #2a2a2a 20%, #0d0d0d 40%, #333333 60%, #1a1a1a 80%, #0a0a0a 100%)" },
  { id: "ag-6", category: "Automotive & Garage", name: "Brushed Aluminum", description: "Brushed aluminum panel texture with industrial sheen", prompt: "Brushed aluminum metal wall panel texture with directional grain and subtle industrial sheen, premium automotive garage interior surface, print-ready seamless", thumbGradient: "linear-gradient(175deg, #b0b0b0 0%, #c8c8c8 30%, #a0a0a0 55%, #bdbdbd 80%, #b5b5b5 100%)" },
];
