/**
 * FROZEN OFFLINE FIXTURE — 2022 Ford F-250 Crew Cab.
 *
 * Every input here is a constant or is derived deterministically from one.
 * There is no provider call, no network read and no database read: the point
 * of the qualification is to prove the deterministic assembly path in
 * isolation, so anything that could vary between two runs is excluded by
 * construction.
 *
 * The creative assets stand in for what DesignPanelAI would return. They are
 * generated by seeded code rather than fetched, because what is under test is
 * the ASSEMBLY of creative material into canonical surfaces -- not the
 * creative material itself.
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const sharp = require("../../runtime/node_modules/sharp");

export const HERE = dirname(fileURLToPath(import.meta.url));
export const ASSET_DIR = join(HERE, "assets");
export const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");

/**
 * Deterministic UUIDs. Same derivation the dormant cycle module uses, so a
 * stable label always yields the same id and two runs agree by construction.
 */
export function uuidFrom(label) {
  const text = sha256(Buffer.from(String(label))).slice(0, 32).split("");
  text[12] = "5";
  text[16] = ["8", "9", "a", "b"][parseInt(text[16], 16) % 4];
  const v = text.join("");
  return `${v.slice(0, 8)}-${v.slice(8, 12)}-${v.slice(12, 16)}-${v.slice(16, 20)}-${v.slice(20)}`;
}

/** GENIE trim dimensions, per the handoff. Inches. */
export const GENIE_TRIM = Object.freeze({
  driver:    { widthInches: 153,  heightInches: 56   },
  passenger: { widthInches: 153,  heightInches: 56   },
  hood:      { widthInches: 71.5, heightInches: 56   },
  roof:      { widthInches: 74.3, heightInches: 54.8 },
  front:     { widthInches: 129,  heightInches: 34   },
  rear:      { widthInches: 76,   heightInches: 54   },
});

export const BLEED_INCHES = 5;

export const VEHICLE = Object.freeze({
  year: 2022, make: "Ford", model: "F-250", configuration: "Crew Cab",
  vehicleId: "2022-ford-f250-crewcab",
  type: "truck",
});

/** The exact customer strings. Spelling authority is this object, not a model. */
export const CUSTOMER_STRINGS = Object.freeze({
  company: "Precision Climate Solutions",
  phone: "555-0142",
  domain: "precisionclimate.com",
});

/**
 * The GENIE dimension manifest, in the shape the Design Master author binds to.
 * `expectedSurfaces` is the authoritative geometry; nothing downstream is
 * allowed to re-derive it.
 */
export function genieManifest() {
  const expectedSurfaces = Object.entries(GENIE_TRIM).map(([surfaceKey, dims]) => ({
    surfaceKey, widthInches: dims.widthInches, heightInches: dims.heightInches,
  }));
  const manifest = { contractVersion: "designpro.genie-manifest.v1", vehicleId: VEHICLE.vehicleId, bleedInches: BLEED_INCHES, expectedSurfaces };
  const manifestHash = sha256(Buffer.from(JSON.stringify(manifest)));
  return { manifest, manifestHash };
}

/** Deterministic surface mappings — one per surface, hash derived from its key. */
export function surfaceMappings() {
  const out = {};
  for (const surfaceKey of Object.keys(GENIE_TRIM)) {
    out[surfaceKey] = {
      mappingId: uuidFrom(`mapping:${VEHICLE.vehicleId}:${surfaceKey}`),
      mappingHash: sha256(Buffer.from(`planar-developable:${VEHICLE.vehicleId}:${surfaceKey}:v1`)),
    };
  }
  return out;
}

/* ------------------------------------------------------------------ *
 * Frozen creative assets. Seeded, so two runs produce identical bytes.
 * ------------------------------------------------------------------ */

/** A tiny deterministic PRNG so the "creative" is reproducible. */
function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * The background field. One continuous piece of artwork spanning the whole
 * authored design space, which is what lets the renderer sample real bleed
 * from authored pixels instead of inventing an edge afterward.
 */
async function buildBackground(widthPx, heightPx, seed = 20260904) {
  const rnd = mulberry32(seed);
  const raw = Buffer.alloc(widthPx * heightPx * 3);
  // A deep blue-to-slate horizontal ramp with a deterministic diagonal banding
  // motif. Chosen so every pixel is opaque and non-white: a full-bleed check
  // that passes on a white field proves nothing.
  for (let y = 0; y < heightPx; y += 1) {
    for (let x = 0; x < widthPx; x += 1) {
      const t = x / Math.max(1, widthPx - 1);
      const band = Math.sin((x * 0.06) + (y * 0.14)) * 0.5 + 0.5;
      const i = (y * widthPx + x) * 3;
      raw[i]     = Math.round(12 + t * 26 + band * 18);
      raw[i + 1] = Math.round(38 + t * 70 + band * 26);
      raw[i + 2] = Math.round(86 + t * 122 + band * 30);
    }
  }
  void rnd;
  return sharp(raw, { raw: { width: widthPx, height: heightPx, channels: 3 } }).png({ compressionLevel: 6, adaptiveFiltering: false, palette: false, force: true }).toBuffer();
}

/** A motif: concentric arcs, deterministic, with alpha. */
async function buildMotif(sizePx, seed = 7731) {
  const rnd = mulberry32(seed);
  const raw = Buffer.alloc(sizePx * sizePx * 4);
  const cx = sizePx / 2, cy = sizePx / 2;
  for (let y = 0; y < sizePx; y += 1) {
    for (let x = 0; x < sizePx; x += 1) {
      const d = Math.hypot(x - cx, y - cy) / (sizePx / 2);
      const ring = Math.abs(Math.sin(d * 9.0));
      const a = d > 1 ? 0 : Math.round(190 * Math.pow(ring, 2.2));
      const i = (y * sizePx + x) * 4;
      raw[i] = 235; raw[i + 1] = 245; raw[i + 2] = 255; raw[i + 3] = a;
    }
  }
  void rnd;
  return sharp(raw, { raw: { width: sizePx, height: sizePx, channels: 4 } }).png({ compressionLevel: 6, adaptiveFiltering: false, palette: false, force: true }).toBuffer();
}

/** The approved logo. Its bytes are the identity; nothing may redraw it. */
async function buildLogo(widthPx, heightPx) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${widthPx}" height="${heightPx}" viewBox="0 0 480 160">
  <rect x="6" y="6" width="468" height="148" rx="18" fill="#ffffff"/>
  <rect x="18" y="18" width="444" height="124" rx="10" fill="#0b2f6b"/>
  <path d="M52 118 L96 42 L140 118 Z" fill="#38bdf8"/>
  <circle cx="188" cy="80" r="30" fill="none" stroke="#38bdf8" stroke-width="10"/>
  <rect x="236" y="52" width="200" height="12" rx="6" fill="#e2f2ff"/>
  <rect x="236" y="76" width="160" height="12" rx="6" fill="#9ecbff"/>
  <rect x="236" y="100" width="120" height="12" rx="6" fill="#5aa9ef"/>
</svg>`;
  return sharp(Buffer.from(svg)).png({ compressionLevel: 6, adaptiveFiltering: false, palette: false, force: true }).toBuffer();
}

/** The pinned font. Read from disk so its bytes are fixed and hashable. */
export const FONT_PATH = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf";

/**
 * Materialise every frozen asset once and return their paths + hashes.
 * Re-running is a no-op when the bytes already match, which keeps the fixture
 * stable across the two clean-process renders the qualification compares.
 */
export async function materializeAssets({ designSpaceWidthIn, designSpaceHeightIn, pxPerInch }) {
  mkdirSync(ASSET_DIR, { recursive: true });
  const bgW = Math.max(1, Math.round(designSpaceWidthIn * pxPerInch));
  const bgH = Math.max(1, Math.round(designSpaceHeightIn * pxPerInch));

  const write = (name, bytes) => {
    const path = join(ASSET_DIR, name);
    if (!existsSync(path) || sha256(readFileSync(path)) !== sha256(bytes)) writeFileSync(path, bytes);
    return { path, contentHash: sha256(bytes), bytes };
  };

  const background = write("background.png", await buildBackground(bgW, bgH));
  const motif = write("motif.png", await buildMotif(1024));
  const logo = write("logo.png", await buildLogo(960, 320));
  const fontBytes = readFileSync(FONT_PATH);
  const font = write("brand-font.ttf", fontBytes);

  return {
    background: { ...background, widthPx: bgW, heightPx: bgH },
    motif: { ...motif, widthPx: 1024, heightPx: 1024 },
    logo: { ...logo, widthPx: 960, heightPx: 320 },
    font,
  };
}
