/**
 * send-password-reset
 *
 * Sends a password-reset email via Resend (verified restyleproai.com domain)
 * using a recovery link generated by the Supabase Admin API.
 *
 * Why this function exists:
 *   Supabase's built-in auth email service (used by
 *   `supabase.auth.resetPasswordForEmail`) is rate-limited to ~4 emails/hour
 *   on the default SMTP config and often silently drops messages. Users
 *   report clicking "Forgot password" and never receiving an email.
 *   Resend on our verified domain is reliable and has no such limits.
 *
 * Flow:
 *   1. Client POSTs { email, redirectTo } to this function.
 *   2. We call auth.admin.generateLink({ type: 'recovery' }) to mint a
 *      one-time action link that, when visited, establishes a recovery
 *      session and redirects to /reset-password.
 *   3. We email that link to the user via Resend from noreply@restyleproai.com.
 *   4. The user clicks the link, lands on /reset-password with an active
 *      session, and can set a new password via supabase.auth.updateUser().
 *
 * This function is public (verify_jwt = false) because the user is logged
 * out when they request a reset. We only reveal whether an email was sent
 * — we do NOT confirm or deny whether the account exists to the caller.
 */

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "https://esm.sh/resend@2.0.0";
import { createExternalClient } from "../_shared/external-db.ts";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface ResetRequest {
  email: string;
  redirectTo?: string;
}

function buildResetEmailHtml(actionLink: string): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#000000;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#000000;">
    <tr><td align="center" style="padding:32px 16px;">
      <table width="600" cellpadding="0" cellspacing="0" style="background-color:#0d0d0d;border:1px solid #1a1a1a;border-radius:12px;overflow:hidden;">

        <tr><td style="padding:32px;background:linear-gradient(135deg,#2563eb,#a855f7);text-align:center;">
          <h1 style="margin:0;font-size:22px;color:#ffffff;font-weight:700;letter-spacing:0.5px;">RestylePro</h1>
          <p style="margin:6px 0 0;font-size:12px;color:#e0e7ff;">Professional Vehicle Wrap Visualization</p>
        </td></tr>

        <tr><td style="padding:32px;">
          <h2 style="margin:0 0 16px;font-size:20px;color:#ffffff;font-weight:600;">Reset your password</h2>
          <p style="margin:0 0 20px;font-size:14px;color:#cccccc;line-height:1.6;">
            We received a request to reset the password for your RestylePro account.
            Click the button below to set a new password. This link expires in 1 hour.
          </p>

          <table cellpadding="0" cellspacing="0" style="margin:24px 0;">
            <tr><td style="background:#00C7FF;border-radius:8px;">
              <a href="${actionLink}" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:#000000;text-decoration:none;">
                Reset Password
              </a>
            </td></tr>
          </table>

          <p style="margin:24px 0 0;font-size:12px;color:#888;line-height:1.6;">
            Or copy and paste this link into your browser:
          </p>
          <p style="margin:6px 0 0;font-size:11px;color:#00C7FF;word-break:break-all;line-height:1.5;">
            ${actionLink}
          </p>

          <p style="margin:32px 0 0;font-size:12px;color:#666;line-height:1.6;">
            If you didn't request a password reset, you can safely ignore this email —
            your password will not change.
          </p>
        </td></tr>

        <tr><td style="padding:24px 32px;border-top:1px solid #1a1a1a;text-align:center;">
          <p style="margin:0;font-size:10px;color:#444;">
            Sent by <span style="color:#00C7FF;font-weight:600;">RestylePro</span> &middot; restyleproai.com
          </p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

function buildResetEmailText(actionLink: string): string {
  return `Reset your RestylePro password

We received a request to reset the password for your RestylePro account.
Open this link to set a new password (expires in 1 hour):

${actionLink}

If you didn't request a password reset, you can safely ignore this email —
your password will not change.

— RestylePro
restyleproai.com`;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email, redirectTo }: ResetRequest = await req.json();

    if (!email || typeof email !== "string") {
      return new Response(
        JSON.stringify({ error: "email is required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const normalizedEmail = email.trim().toLowerCase();
    const finalRedirect = redirectTo || "https://restyleproai.com/reset-password";

    const supabaseAdmin = createExternalClient();

    // Generate a recovery action link. If the user doesn't exist, Supabase
    // returns an error — we catch it and still respond success to the client
    // to avoid account enumeration.
    const { data, error } = await supabaseAdmin.auth.admin.generateLink({
      type: "recovery",
      email: normalizedEmail,
      options: { redirectTo: finalRedirect },
    });

    if (error || !data?.properties?.action_link) {
      console.warn(
        `[send-password-reset] generateLink returned no link for ${normalizedEmail}:`,
        error?.message || "no action_link",
      );
      // Always respond success so we don't leak which emails are registered.
      return new Response(
        JSON.stringify({ success: true }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const actionLink = data.properties.action_link;

    const emailResponse = await resend.emails.send({
      from: "RestylePro <noreply@restyleproai.com>",
      to: [normalizedEmail],
      subject: "Reset your RestylePro password",
      html: buildResetEmailHtml(actionLink),
      text: buildResetEmailText(actionLink),
    });

    if (emailResponse.error) {
      console.error("[send-password-reset] Resend error:", emailResponse.error);
      return new Response(
        JSON.stringify({
          error: emailResponse.error.message || "Failed to send reset email",
        }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    console.log(
      `[send-password-reset] Reset email sent to ${normalizedEmail}, id=${emailResponse.data?.id}`,
    );

    return new Response(
      JSON.stringify({ success: true, messageId: emailResponse.data?.id }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (err: any) {
    console.error("[send-password-reset] Unhandled error:", err);
    return new Response(
      JSON.stringify({ error: err?.message || "Internal error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
};

serve(handler);
